version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: weekly
    groups:
      runtime:
        dependency-type: production
      development:
        dependency-type: development
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major
