import { defineConfig } from "react-doctor/api";

export default defineConfig({
  blocking: "warning",
  buckets: {
    "compiler-cleanup": "error",
  },
  categories: {
    Accessibility: "error",
    Bugs: "error",
    Maintainability: "error",
    Performance: "error",
    Security: "error",
  },
  // Registry entries and Astro islands are discovered outside Doctor's static
  // React import graph. TypeScript, Biome, and production builds cover them.
  deadCode: false,
  ignore: {
    files: [
      ".blume/**",
      ".blume-verify/**",
      "build/**",
      "conformance/gen/**",
      "dist/**",
      "examples/gen/**",
      "public/r/**",
      "registry/**/__golden__/**",
      "registry/**/gen/**",
      "registry/base-nova/protoform/lib/protobuf-v1-bridge/**",
      "**/*_form.ts",
      "**/*_pb.ts",
      "**/routeTree.gen.ts",
    ],
    overrides: [
      {
        // Installable registry modules import through their declared public
        // item boundaries so the registry can resolve dependencies.
        files: ["registry/base-nova/protoform/**"],
        rules: ["react-doctor/no-barrel-import"],
      },
      {
        // These standalone animation primitives cannot assume that consumers
        // mounted a shared LazyMotion provider.
        files: [
          "registry/base-nova/protoform/components/card/index.tsx",
          "registry/base-nova/protoform/components/checkbox/index.tsx",
          "registry/base-nova/protoform/components/choicebox/index.tsx",
          "registry/base-nova/protoform/components/collapsible/index.tsx",
          "registry/base-nova/protoform/components/copy-button/index.tsx",
          "registry/base-nova/protoform/components/popover/index.tsx",
          "registry/base-nova/protoform/components/radio-group/index.tsx",
          "registry/base-nova/protoform/components/tabs/index.tsx",
          "registry/base-nova/protoform/components/toggle-group/index.tsx",
          "registry/base-nova/protoform/components/tooltip/index.tsx",
        ],
        rules: ["react-doctor/use-lazy-motion"],
      },
      {
        // Measured auto-height and selection-indicator motion intentionally
        // animates geometry; transform-only motion changes the interaction.
        files: [
          "registry/base-nova/protoform/components/collapsible/index.tsx",
          "registry/base-nova/protoform/components/tabs/index.tsx",
          "registry/base-nova/protoform/components/toggle-group/index.tsx",
        ],
        rules: ["react-doctor/no-layout-property-animation"],
      },
      {
        // Schema editors are cohesive orchestration surfaces. Their logic is
        // already split into hooks and helpers at stable domain boundaries.
        files: [
          "registry/base-nova/protoform/components/auto-form/auto-form-core.tsx",
          "registry/base-nova/protoform/components/combobox/index.tsx",
          "registry/base-nova/protoform/components/json-field/index.tsx",
        ],
        rules: ["react-doctor/no-giant-component"],
      },
      {
        // These lists are positional editors, decorations, or fixed render
        // slots without stable domain identifiers.
        files: [
          "registry/base-nova/protoform/components/auto-form/renderers/index.tsx",
          "registry/base-nova/protoform/components/group/index.tsx",
          "registry/base-nova/protoform/components/json-field/index.tsx",
          "registry/base-nova/protoform/components/key-value-field/index.tsx",
          "registry/base-nova/protoform/components/toggle-group/index.tsx",
        ],
        rules: ["react-doctor/no-array-index-as-key"],
      },
      {
        // Card text convenience is a documented public polymorphic API.
        files: ["registry/base-nova/protoform/components/card/index.tsx"],
        rules: ["react-doctor/no-polymorphic-children"],
      },
      {
        // Controlled adapters intentionally synchronize external snapshots;
        // replacing this with derived state would break dirty tracking.
        files: [
          "registry/base-nova/protoform/components/auto-form/adapters/tanstack-v2.tsx",
          "registry/base-nova/protoform/components/auto-form/auto-form-core.tsx",
          "registry/base-nova/protoform/components/auto-form/field-wrapper.tsx",
          "registry/base-nova/protoform/components/json-field/index.tsx",
          "registry/base-nova/protoform/components/input/index.tsx",
          "registry/base-nova/protoform/lib/base-ui-compat/index.tsx",
        ],
        rules: [
          "react-doctor/no-adjust-state-on-prop-change",
          "react-doctor/no-derived-state",
          "react-doctor/no-derived-state-effect",
          "react-doctor/no-effect-chain",
        ],
      },
      {
        // These composite controls retain native keyboard focus on their
        // contained input; nested native buttons would be invalid HTML.
        files: [
          "registry/base-nova/protoform/components/input-group/index.tsx",
          "registry/base-nova/protoform/components/multi-select/index.tsx",
        ],
        rules: ["react-doctor/no-static-element-interactions", "react-doctor/prefer-tag-over-role"],
      },
      {
        // The combobox bridge reports collection state to its owning primitive.
        files: ["registry/base-nova/protoform/components/combobox/index.tsx"],
        rules: ["react-doctor/no-pass-data-to-parent"],
      },
      {
        // These error records are populated from live form state below their
        // declarations; they are not module-scope static values.
        files: [
          "registry/base-nova/protoform/components/auto-form/adapters/tanstack-v2.tsx",
          "registry/base-nova/protoform/components/auto-form/adapters/tanstack.tsx",
        ],
        rules: ["react-doctor/prefer-module-scope-static-value"],
      },
      {
        // Registry components are intentionally colocated into atomic install units. The
        // listed demos likewise keep private presentation helpers beside their only caller.
        files: [
          "registry/base-nova/protoform/components/**",
          "registry/base-nova/protoform/demo/bookstore/**",
          "components/docs/diagram-maximizer.tsx",
          "examples/basic/basic-form.tsx",
          "examples/complex/complex-form.tsx",
          "examples/kitchen-sink/kitchen-sink-form.tsx",
          "examples/presets/preset-lab.tsx",
          "examples/readiness/readiness-dashboard.tsx",
        ],
        rules: ["react-doctor/no-multi-comp"],
      },
      {
        // Public primitives and adapters must forward consumer-owned native props. Listing
        // every DOM prop would narrow their declared React component contracts.
        files: [
          "registry/base-nova/protoform/components/**",
          "registry/base-nova/protoform/demo/bookstore/**",
          "registry/base-nova/protoform/demo/catalog/final-form.tsx",
          "registry/base-nova/protoform/hooks/**/*.test.tsx",
          "registry/base-nova/protoform/lib/base-ui-compat/**",
          "examples/form-libraries/final-form.tsx",
          "examples/presets/preset-lab.tsx",
        ],
        rules: ["react-doctor/jsx-props-no-spreading"],
      },
      {
        // Form field adapters pass the owning library's registered blur callback through
        // unchanged, so there is no local action-oriented handler to rename.
        files: ["registry/base-nova/protoform/components/auto-form/fields/**"],
        rules: ["react-doctor/jsx-handler-names"],
      },
      {
        // These lazy resource initializers intentionally use the value-only useState form;
        // replacing them with render-time allocation would discard stable client state.
        files: [
          "examples/basic/basic-form.tsx",
          "examples/presets/preset-lab.tsx",
          "registry/base-nova/protoform/components/multi-select/index.tsx",
          "registry/base-nova/protoform/demo/bookstore/bookstore-demo.tsx",
        ],
        rules: ["react-doctor/hook-use-state"],
      },
      {
        // Framer Motion composes these individual transform values into compositor-backed
        // transform strings; hand-building strings would remove its interpolation semantics.
        files: [
          "registry/base-nova/protoform/components/checkbox/index.tsx",
          "registry/base-nova/protoform/components/choicebox/index.tsx",
          "registry/base-nova/protoform/components/copy-button/index.tsx",
          "registry/base-nova/protoform/components/popover/index.tsx",
          "registry/base-nova/protoform/components/radio-group/index.tsx",
          "registry/base-nova/protoform/components/tooltip/index.tsx",
        ],
        rules: ["react-doctor/prefer-motion-transform-property"],
      },
      {
        // Slot-compatible primitives must inspect and clone their single child to merge refs,
        // events, accessibility attributes, and consumer props without an extra DOM wrapper.
        files: [
          "registry/base-nova/protoform/components/auto-form/renderers/index.tsx",
          "registry/base-nova/protoform/components/group/index.tsx",
          "registry/base-nova/protoform/components/popover/index.tsx",
          "registry/base-nova/protoform/components/tabs/index.tsx",
          "registry/base-nova/protoform/components/toggle-group/index.tsx",
          "registry/base-nova/protoform/lib/base-ui-compat/index.tsx",
        ],
        rules: ["react-doctor/no-clone-element", "react-doctor/no-react-children"],
      },
      {
        // Every raw demo source is a separate lazy virtual module whose component closes over
        // that module's source. Object.assign supplies the display name, but Doctor cannot
        // resolve it through the dynamic import factory.
        files: ["examples/catalog/demo-hub.tsx"],
        rules: ["react-doctor/display-name"],
      },
    ],
  },
  lint: true,
  noScore: true,
  respectInlineDisables: false,
  rules: {
    "react-doctor/aria-braille-equivalent": "error",
    "react-doctor/data-table-requires-accessible-name": "error",
    "react-doctor/design-no-em-dash-in-jsx-text": "error",
    "react-doctor/design-no-redundant-padding-axes": "error",
    "react-doctor/design-no-redundant-size-axes": "error",
    "react-doctor/design-no-space-on-flex-children": "error",
    "react-doctor/design-no-three-period-ellipsis": "error",
    "react-doctor/design-no-vague-button-label": "error",
    "react-doctor/details-requires-summary": "error",
    "react-doctor/display-name": "error",
    "react-doctor/empty-table-header": "error",
    "react-doctor/fieldset-requires-legend": "error",
    "react-doctor/forbid-component-props": "error",
    "react-doctor/form-control-requires-name": "error",
    "react-doctor/hook-use-state": "error",
    "react-doctor/html-xml-lang-mismatch": "error",
    "react-doctor/iframe-title-unique": "error",
    "react-doctor/ink-newline-inside-text": "error",
    "react-doctor/ink-prefer-use-paste": "error",
    "react-doctor/ink-suspense-requires-concurrent": "error",
    "react-doctor/jsx-boolean-value": "error",
    "react-doctor/jsx-curly-brace-presence": "error",
    "react-doctor/jsx-filename-extension": "error",
    "react-doctor/jsx-fragments": "error",
    "react-doctor/jsx-handler-names": "error",
    "react-doctor/jsx-no-useless-fragment": "error",
    "react-doctor/jsx-pascal-case": "error",
    "react-doctor/jsx-props-no-spreading": "error",
    "react-doctor/loading-action-preserves-trigger": "error",
    "react-doctor/no-all-caps-body-text": "error",
    "react-doctor/no-arbitrary-px-font-size": "error",
    "react-doctor/no-aria-hidden-on-body": "error",
    "react-doctor/no-aria-invalid-without-description": "error",
    "react-doctor/no-array-index-key": "error",
    "react-doctor/no-auto-scrolling-content": "error",
    "react-doctor/no-cascading-set-state": "error",
    "react-doctor/no-clipped-overlay": "error",
    "react-doctor/no-clone-element": "error",
    "react-doctor/no-collapse-request-error-to-empty-state": "error",
    "react-doctor/no-common-root-font": "error",
    "react-doctor/no-controlled-selection-focus-effect": "error",
    "react-doctor/no-cramped-container-padding": "error",
    "react-doctor/no-crushed-letter-spacing": "error",
    "react-doctor/no-danger": "error",
    "react-doctor/no-dark-mode-glow": "error",
    "react-doctor/no-decorative-blur-orb": "error",
    "react-doctor/no-decorative-grid-background": "error",
    "react-doctor/no-decorative-pulse": "error",
    "react-doctor/no-decorative-radial-spotlight": "error",
    "react-doctor/no-default-purple-page-gradient": "error",
    "react-doctor/no-default-warm-page-surface": "error",
    "react-doctor/no-deprecated-tailwind-class": "error",
    "react-doctor/no-disabled-zoom": "error",
    "react-doctor/no-duplicate-static-id-reference": "error",
    "react-doctor/no-dynamic-tailwind-class-fragment": "error",
    "react-doctor/no-ease-in-motion": "error",
    "react-doctor/no-emoji-heading-decoration": "error",
    "react-doctor/no-empty-card-shell": "error",
    "react-doctor/no-excessive-card-surfaces": "error",
    "react-doctor/no-excessive-centered-copy": "error",
    "react-doctor/no-excessive-font-families": "error",
    "react-doctor/no-excessive-motion-stagger": "error",
    "react-doctor/no-excessive-pill-treatment": "error",
    "react-doctor/no-fake-browser-chrome": "error",
    "react-doctor/no-fixed-inside-transformed-ancestor": "error",
    "react-doctor/no-flat-page-type-scale": "error",
    "react-doctor/no-focus-in-animation-completion-handler": "error",
    "react-doctor/no-focusable-content-in-role-text": "error",
    "react-doctor/no-full-viewport-centered-hero": "error",
    "react-doctor/no-full-viewport-width": "error",
    "react-doctor/no-generic-handler-names": "error",
    "react-doctor/no-generic-marketing-copy": "error",
    "react-doctor/no-generic-purple-blue-icon-gradient": "error",
    "react-doctor/no-gradient-text": "error",
    "react-doctor/no-gray-on-colored-background": "error",
    "react-doctor/no-hairline-border-wide-shadow": "error",
    "react-doctor/no-hero-eyebrow-chip": "error",
    "react-doctor/no-hover-only-reveal": "error",
    "react-doctor/no-icon-tile-heading-stack": "error",
    "react-doctor/no-image-hover-transform": "error",
    "react-doctor/no-img-without-dimensions": "error",
    "react-doctor/no-inert-pointer-affordance": "error",
    "react-doctor/no-inert-sticky-position": "error",
    "react-doctor/no-inline-bounce-easing": "error",
    "react-doctor/no-inline-exhaustive-style": "error",
    "react-doctor/no-invisible-focus-control": "error",
    "react-doctor/no-italic-serif-display-heading": "error",
    "react-doctor/no-justified-text": "error",
    "react-doctor/no-layout-shifting-interaction-state": "error",
    "react-doctor/no-layout-transition-inline": "error",
    "react-doctor/no-long-transition-duration": "error",
    "react-doctor/no-low-contrast-inline-style": "error",
    "react-doctor/no-manufactured-contrast-copy": "error",
    "react-doctor/no-mixed-animation-owners": "error",
    "react-doctor/no-mixed-icon-libraries": "error",
    "react-doctor/no-monotonous-page-spacing": "error",
    "react-doctor/no-multi-comp": "error",
    "react-doctor/no-nested-card-surface": "error",
    "react-doctor/no-nonresizable-textarea": "error",
    "react-doctor/no-numbered-section-markers": "error",
    "react-doctor/no-outline-none": "error",
    "react-doctor/no-overloaded-hover-state": "error",
    "react-doctor/no-oversized-long-heading": "error",
    "react-doctor/no-overwide-text-measure": "error",
    "react-doctor/no-passive-request-owner-ref": "error",
    "react-doctor/no-pill-navigation-count": "error",
    "react-doctor/no-placeholder-persona-copy": "error",
    "react-doctor/no-pointer-disabled-enabled-control": "error",
    "react-doctor/no-presentation-role-conflict": "error",
    "react-doctor/no-prop-types": "error",
    "react-doctor/no-pulsing-status-dot": "error",
    "react-doctor/no-pure-black-background": "error",
    "react-doctor/no-pure-black-shadow": "error",
    "react-doctor/no-radial-halo": "error",
    "react-doctor/no-react-children": "error",
    "react-doctor/no-reduced-motion-content-removal": "error",
    "react-doctor/no-redundant-display-class": "error",
    "react-doctor/no-redundant-title-tooltip": "error",
    "react-doctor/no-repeated-container-text": "error",
    "react-doctor/no-repeated-emoji-tiles": "error",
    "react-doctor/no-repeated-glass-surfaces": "error",
    "react-doctor/no-repeated-hover-scale": "error",
    "react-doctor/no-repeated-kicker-labels": "error",
    "react-doctor/no-repeated-placeholder-navigation": "error",
    "react-doctor/no-repeated-section-shells": "error",
    "react-doctor/no-repeating-gradient-decoration": "error",
    "react-doctor/no-server-side-image-map": "error",
    "react-doctor/no-set-state": "error",
    "react-doctor/no-shape-assembled-illustration": "error",
    "react-doctor/no-side-tab-border": "error",
    "react-doctor/no-skipped-heading-level": "error",
    "react-doctor/no-small-form-control-text": "error",
    "react-doctor/no-smooth-scroll-without-reduced-motion": "error",
    "react-doctor/no-svg-currentcolor-with-fill-class": "error",
    "react-doctor/no-symmetric-text-button-padding": "error",
    "react-doctor/no-tailwind-layout-transition": "error",
    "react-doctor/no-tight-all-caps-heading": "error",
    "react-doctor/no-tight-body-leading": "error",
    "react-doctor/no-tight-display-tracking": "error",
    "react-doctor/no-tiny-text": "error",
    "react-doctor/no-tiny-uppercase-tracked-label": "error",
    "react-doctor/no-transitioned-composite-widget-state": "error",
    "react-doctor/no-transitioned-focus-ring": "error",
    "react-doctor/no-unbounded-animation-frame-loop": "error",
    "react-doctor/no-undersized-icon-button": "error",
    "react-doctor/no-unescaped-entities": "error",
    "react-doctor/no-ungated-tailwind-animation": "error",
    "react-doctor/no-uniform-feature-card-grid": "error",
    "react-doctor/no-uppercase-mono-label": "error",
    "react-doctor/no-uppercase-tracked-navigation-label": "error",
    "react-doctor/no-wide-letter-spacing": "error",
    "react-doctor/no-z-index-9999": "error",
    "react-doctor/prefer-dvh-over-vh": "error",
    "react-doctor/prefer-es6-class": "error",
    "react-doctor/prefer-function-component": "error",
    "react-doctor/prefer-motion-transform-property": "error",
    "react-doctor/prefer-tabular-numeric-data": "error",
    "react-doctor/prefer-truncate-shorthand": "error",
    "react-doctor/react-in-jsx-scope": "off",
    "react-doctor/require-autoplay-video-poster": "error",
    "react-doctor/require-scale-reveal-transform-origin": "error",
    "react-doctor/self-closing-comp": "error",
    "react-doctor/shadcn-tabs-trigger-requires-list": "error",
    "react-doctor/state-in-constructor": "error",
    "react-doctor/styled-components-duplicate-css-property-in-block": "error",
  },
  scope: "full",
  share: false,
  supplyChain: {
    enabled: false,
  },
  surfaces: {
    ciFailure: {
      includeFileContexts: ["test", "story"],
      includeTags: ["design"],
    },
    cli: {
      includeFileContexts: ["test", "story"],
      includeTags: ["design"],
    },
    prComment: {
      includeFileContexts: ["test", "story"],
      includeTags: ["design"],
    },
    score: {
      includeFileContexts: ["test", "story"],
      includeTags: ["design"],
    },
  },
  verbose: true,
  warnings: true,
});
