import { defineConfig } from "react-doctor/api";

export default defineConfig({
  blocking: "warning",
  // Registry entries and Astro islands are discovered outside Doctor's static
  // React import graph. TypeScript, Biome, and production builds cover them.
  deadCode: false,
  ignore: {
    files: [
      ".blume/**",
      ".blume-verify/**",
      "build/**",
      "conformance/gen/**",
      "dist/**",
      "examples/gen/**",
      "public/r/**",
      "registry/**/__golden__/**",
      "registry/**/gen/**",
      "registry/base-nova/protoform/lib/protobuf-v1-bridge/**",
      "**/*_form.ts",
      "**/*_pb.ts",
      "**/routeTree.gen.ts",
    ],
    overrides: [
      {
        // Installable registry modules import through their declared public
        // item boundaries so the registry can resolve dependencies.
        files: ["registry/base-nova/protoform/**"],
        rules: ["react-doctor/no-barrel-import"],
      },
      {
        // These standalone animation primitives cannot assume that consumers
        // mounted a shared LazyMotion provider.
        files: [
          "registry/base-nova/protoform/components/card/index.tsx",
          "registry/base-nova/protoform/components/checkbox/index.tsx",
          "registry/base-nova/protoform/components/choicebox/index.tsx",
          "registry/base-nova/protoform/components/collapsible/index.tsx",
          "registry/base-nova/protoform/components/copy-button/index.tsx",
          "registry/base-nova/protoform/components/popover/index.tsx",
          "registry/base-nova/protoform/components/radio-group/index.tsx",
          "registry/base-nova/protoform/components/tabs/index.tsx",
          "registry/base-nova/protoform/components/toggle-group/index.tsx",
          "registry/base-nova/protoform/components/tooltip/index.tsx",
        ],
        rules: ["react-doctor/use-lazy-motion"],
      },
      {
        // Measured auto-height and selection-indicator motion intentionally
        // animates geometry; transform-only motion changes the interaction.
        files: [
          "registry/base-nova/protoform/components/collapsible/index.tsx",
          "registry/base-nova/protoform/components/tabs/index.tsx",
          "registry/base-nova/protoform/components/toggle-group/index.tsx",
        ],
        rules: ["react-doctor/no-layout-property-animation"],
      },
      {
        // Schema editors are cohesive orchestration surfaces. Their logic is
        // already split into hooks and helpers at stable domain boundaries.
        files: [
          "registry/base-nova/protoform/components/auto-form/auto-form-core.tsx",
          "registry/base-nova/protoform/components/combobox/index.tsx",
          "registry/base-nova/protoform/components/json-field/index.tsx",
        ],
        rules: ["react-doctor/no-giant-component"],
      },
      {
        // These lists are positional editors, decorations, or fixed render
        // slots without stable domain identifiers.
        files: [
          "registry/base-nova/protoform/components/auto-form/renderers/index.tsx",
          "registry/base-nova/protoform/components/group/index.tsx",
          "registry/base-nova/protoform/components/json-field/index.tsx",
          "registry/base-nova/protoform/components/key-value-field/index.tsx",
          "registry/base-nova/protoform/components/toggle-group/index.tsx",
        ],
        rules: ["react-doctor/no-array-index-as-key"],
      },
      {
        // Card text convenience is a documented public polymorphic API.
        files: ["registry/base-nova/protoform/components/card/index.tsx"],
        rules: ["react-doctor/no-polymorphic-children"],
      },
      {
        // Controlled adapters intentionally synchronize external snapshots;
        // replacing this with derived state would break dirty tracking.
        files: [
          "registry/base-nova/protoform/components/auto-form/adapters/tanstack-v2.tsx",
          "registry/base-nova/protoform/components/auto-form/auto-form-core.tsx",
          "registry/base-nova/protoform/components/auto-form/field-wrapper.tsx",
          "registry/base-nova/protoform/components/json-field/index.tsx",
          "registry/base-nova/protoform/components/input/index.tsx",
          "registry/base-nova/protoform/lib/base-ui-compat/index.tsx",
        ],
        rules: [
          "react-doctor/no-adjust-state-on-prop-change",
          "react-doctor/no-derived-state",
          "react-doctor/no-derived-state-effect",
          "react-doctor/no-effect-chain",
        ],
      },
      {
        // These composite controls retain native keyboard focus on their
        // contained input; nested native buttons would be invalid HTML.
        files: [
          "registry/base-nova/protoform/components/input-group/index.tsx",
          "registry/base-nova/protoform/components/multi-select/index.tsx",
        ],
        rules: ["react-doctor/no-static-element-interactions", "react-doctor/prefer-tag-over-role"],
      },
      {
        // The combobox bridge reports collection state to its owning primitive.
        files: ["registry/base-nova/protoform/components/combobox/index.tsx"],
        rules: ["react-doctor/no-pass-data-to-parent"],
      },
      {
        // These error records are populated from live form state below their
        // declarations; they are not module-scope static values.
        files: [
          "registry/base-nova/protoform/components/auto-form/adapters/tanstack-v2.tsx",
          "registry/base-nova/protoform/components/auto-form/adapters/tanstack.tsx",
        ],
        rules: ["react-doctor/prefer-module-scope-static-value"],
      },
      {
        // Registry components are intentionally colocated into atomic install units. The
        // listed demos likewise keep private presentation helpers beside their only caller.
        files: [
          "registry/base-nova/protoform/components/**",
          "registry/base-nova/protoform/demo/bookstore/**",
          "components/docs/diagram-maximizer.tsx",
          "examples/basic/basic-form.tsx",
          "examples/complex/complex-form.tsx",
          "examples/kitchen-sink/kitchen-sink-form.tsx",
          "examples/presets/preset-lab.tsx",
          "examples/readiness/readiness-dashboard.tsx",
        ],
        rules: ["react-doctor/no-multi-comp"],
      },
      {
        // Public primitives and adapters must forward consumer-owned native props. Listing
        // every DOM prop would narrow their declared React component contracts.
        files: [
          "registry/base-nova/protoform/components/**",
          "registry/base-nova/protoform/demo/bookstore/**",
          "registry/base-nova/protoform/demo/catalog/final-form.tsx",
          "registry/base-nova/protoform/hooks/**/*.test.tsx",
          "registry/base-nova/protoform/lib/base-ui-compat/**",
          "examples/form-libraries/final-form.tsx",
          "examples/presets/preset-lab.tsx",
        ],
        rules: ["react-doctor/jsx-props-no-spreading"],
      },
      {
        // Form field adapters pass the owning library's registered blur callback through
        // unchanged, so there is no local action-oriented handler to rename.
        files: ["registry/base-nova/protoform/components/auto-form/fields/**"],
        rules: ["react-doctor/jsx-handler-names"],
      },
      {
        // These lazy resource initializers intentionally use the value-only useState form;
        // replacing them with render-time allocation would discard stable client state.
        files: [
          "examples/basic/basic-form.tsx",
          "examples/presets/preset-lab.tsx",
          "registry/base-nova/protoform/components/multi-select/index.tsx",
          "registry/base-nova/protoform/demo/bookstore/bookstore-demo.tsx",
        ],
        rules: ["react-doctor/hook-use-state"],
      },
      {
        // Framer Motion composes these individual transform values into compositor-backed
        // transform strings; hand-building strings would remove its interpolation semantics.
        files: [
          "registry/base-nova/protoform/components/checkbox/index.tsx",
          "registry/base-nova/protoform/components/choicebox/index.tsx",
          "registry/base-nova/protoform/components/copy-button/index.tsx",
          "registry/base-nova/protoform/components/popover/index.tsx",
          "registry/base-nova/protoform/components/radio-group/index.tsx",
          "registry/base-nova/protoform/components/tooltip/index.tsx",
        ],
        rules: ["react-doctor/prefer-motion-transform-property"],
      },
      {
        // Slot-compatible primitives must inspect and clone their single child to merge refs,
        // events, accessibility attributes, and consumer props without an extra DOM wrapper.
        files: [
          "registry/base-nova/protoform/components/auto-form/renderers/index.tsx",
          "registry/base-nova/protoform/components/group/index.tsx",
          "registry/base-nova/protoform/components/popover/index.tsx",
          "registry/base-nova/protoform/components/tabs/index.tsx",
          "registry/base-nova/protoform/components/toggle-group/index.tsx",
          "registry/base-nova/protoform/lib/base-ui-compat/index.tsx",
        ],
        rules: ["react-doctor/no-clone-element", "react-doctor/no-react-children"],
      },
      {
        // Every raw demo source is a separate lazy virtual module whose component closes over
        // that module's source. Object.assign supplies the display name, but Doctor cannot
        // resolve it through the dynamic import factory.
        files: ["examples/catalog/demo-hub.tsx"],
        rules: ["react-doctor/display-name"],
      },
    ],
  },
  lint: true,
  noScore: true,
  respectInlineDisables: false,
  rules: {
    // Every installed React Doctor rule is listed explicitly. The modern JSX-transform
    // compatibility rule below is the only rule that remains off.
    "react-doctor/active-static-asset": "error",
    "react-doctor/activity-wraps-effect-heavy-subtree": "error",
    "react-doctor/advanced-event-handler-refs": "error",
    "react-doctor/agent-tool-capability-risk": "error",
    "react-doctor/alt-text": "error",
    "react-doctor/anchor-ambiguous-text": "error",
    "react-doctor/anchor-has-content": "error",
    "react-doctor/anchor-is-valid": "error",
    "react-doctor/anchor-target-exists": "error",
    "react-doctor/aria-activedescendant-has-tabindex": "error",
    "react-doctor/aria-braille-equivalent": "error",
    "react-doctor/aria-props": "error",
    "react-doctor/aria-proptypes": "error",
    "react-doctor/aria-role": "error",
    "react-doctor/aria-unsupported-elements": "error",
    "react-doctor/artifact-baas-authority-surface": "error",
    "react-doctor/artifact-env-leak": "error",
    "react-doctor/artifact-secret-leak": "error",
    "react-doctor/async-await-in-loop": "error",
    "react-doctor/async-defer-await": "error",
    "react-doctor/async-parallel": "error",
    "react-doctor/auth-token-in-web-storage": "error",
    "react-doctor/autocomplete-valid": "error",
    "react-doctor/build-pipeline-secret-boundary": "error",
    "react-doctor/button-has-type": "error",
    "react-doctor/checked-requires-onchange-or-readonly": "error",
    "react-doctor/class-component-missing-component-will-unmount-teardown": "error",
    "react-doctor/click-events-have-key-events": "error",
    "react-doctor/clickjacking-redirect-risk": "error",
    "react-doctor/client-localstorage-no-version": "error",
    "react-doctor/client-passive-event-listeners": "error",
    "react-doctor/command-execution-input-risk": "error",
    "react-doctor/context-provider-value-from-unmemoized-local-literal": "error",
    "react-doctor/control-has-associated-label": "error",
    "react-doctor/cors-cookie-trust-risk": "error",
    "react-doctor/dangerous-html-sink": "error",
    "react-doctor/data-table-requires-accessible-name": "error",
    "react-doctor/debounce-no-cleanup": "error",
    "react-doctor/design-no-em-dash-in-jsx-text": "error",
    "react-doctor/design-no-redundant-padding-axes": "error",
    "react-doctor/design-no-redundant-size-axes": "error",
    "react-doctor/design-no-space-on-flex-children": "error",
    "react-doctor/design-no-three-period-ellipsis": "error",
    "react-doctor/design-no-vague-button-label": "error",
    "react-doctor/details-requires-summary": "error",
    "react-doctor/dialog-has-accessible-name": "error",
    "react-doctor/display-name": "error",
    "react-doctor/effect-listener-cleanup-mismatch": "error",
    "react-doctor/effect-listener-cleanup-reference-mismatch": "error",
    "react-doctor/effect-needs-cleanup": "error",
    "react-doctor/effect-observer-needs-disconnect": "error",
    "react-doctor/effect-raf-loop-needs-cancel": "error",
    "react-doctor/effect-remove-listener-inline-handler": "error",
    "react-doctor/empty-table-header": "error",
    "react-doctor/exhaustive-deps": "error",
    "react-doctor/expo-no-non-inlined-env": "error",
    "react-doctor/fieldset-requires-legend": "error",
    "react-doctor/firebase-client-owned-authz-field": "error",
    "react-doctor/firebase-permissive-rules": "error",
    "react-doctor/firebase-query-filter-as-auth": "error",
    "react-doctor/forbid-component-props": "error",
    "react-doctor/forbid-dom-props": "error",
    "react-doctor/forbid-elements": "error",
    "react-doctor/form-control-requires-name": "error",
    "react-doctor/forward-ref-uses-ref": "error",
    "react-doctor/git-provider-url-injection-risk": "error",
    "react-doctor/heading-has-content": "error",
    "react-doctor/hook-import-rename-loses-use-prefix": "error",
    "react-doctor/hook-use-state": "error",
    "react-doctor/hooks-no-nan-in-deps": "error",
    "react-doctor/html-has-lang": "error",
    "react-doctor/html-label-has-single-control": "error",
    "react-doctor/html-no-invalid-paragraph-child": "error",
    "react-doctor/html-no-invalid-table-nesting": "error",
    "react-doctor/html-no-nested-form": "error",
    "react-doctor/html-no-nested-interactive": "error",
    "react-doctor/html-xml-lang-mismatch": "error",
    "react-doctor/iframe-has-title": "error",
    "react-doctor/iframe-missing-sandbox": "error",
    "react-doctor/iframe-title-unique": "error",
    "react-doctor/img-redundant-alt": "error",
    "react-doctor/import-metadata-execution-risk": "error",
    "react-doctor/ink-ctrl-c-handler-requires-exit-option": "error",
    "react-doctor/ink-newline-inside-text": "error",
    "react-doctor/ink-no-bare-process-exit": "error",
    "react-doctor/ink-no-direct-raw-mode": "error",
    "react-doctor/ink-no-dom-host-elements": "error",
    "react-doctor/ink-no-dom-router": "error",
    "react-doctor/ink-no-focus-in-render": "error",
    "react-doctor/ink-no-layout-inside-text": "error",
    "react-doctor/ink-no-live-hooks-in-render-to-string": "error",
    "react-doctor/ink-no-measure-element-in-render": "error",
    "react-doctor/ink-no-multiple-static": "error",
    "react-doctor/ink-no-raw-text": "error",
    "react-doctor/ink-no-repeated-render": "error",
    "react-doctor/ink-prefer-use-animation": "error",
    "react-doctor/ink-prefer-use-paste": "error",
    "react-doctor/ink-static-is-append-only": "error",
    "react-doctor/ink-static-requires-key": "error",
    "react-doctor/ink-suspense-requires-concurrent": "error",
    "react-doctor/ink-use-reactive-window-size": "error",
    "react-doctor/ink-use-string-width-for-cursor": "error",
    "react-doctor/ink-use-suspend-terminal": "error",
    "react-doctor/ink-valid-aria-semantics": "error",
    "react-doctor/insecure-crypto-risk": "error",
    "react-doctor/insecure-session-cookie": "error",
    "react-doctor/interactive-supports-focus": "error",
    "react-doctor/jotai-derived-atom-returns-fresh-object": "error",
    "react-doctor/jotai-select-atom-in-render-body": "error",
    "react-doctor/jotai-tq-use-raw-query-atom": "error",
    "react-doctor/js-async-reduce-without-awaited-acc": "error",
    "react-doctor/js-batch-dom-css": "error",
    "react-doctor/js-cache-property-access": "error",
    "react-doctor/js-cache-storage": "error",
    "react-doctor/js-combine-iterations": "error",
    "react-doctor/js-early-exit": "error",
    "react-doctor/js-flatmap-filter": "error",
    "react-doctor/js-hoist-intl": "error",
    "react-doctor/js-hoist-regexp": "error",
    "react-doctor/js-index-maps": "error",
    "react-doctor/js-length-check-first": "error",
    "react-doctor/js-min-max-loop": "error",
    "react-doctor/js-set-map-lookups": "error",
    "react-doctor/js-tosorted-immutable": "error",
    "react-doctor/jsx-boolean-value": "error",
    "react-doctor/jsx-curly-brace-presence": "error",
    "react-doctor/jsx-filename-extension": "error",
    "react-doctor/jsx-fragments": "error",
    "react-doctor/jsx-handler-names": "error",
    "react-doctor/jsx-key": "error",
    "react-doctor/jsx-max-depth": "error",
    "react-doctor/jsx-no-comment-textnodes": "error",
    "react-doctor/jsx-no-constructed-context-values": "error",
    "react-doctor/jsx-no-duplicate-props": "error",
    "react-doctor/jsx-no-jsx-as-prop": "error",
    "react-doctor/jsx-no-new-array-as-prop": "error",
    "react-doctor/jsx-no-new-function-as-prop": "error",
    "react-doctor/jsx-no-new-object-as-prop": "error",
    "react-doctor/jsx-no-script-url": "error",
    "react-doctor/jsx-no-target-blank": "error",
    "react-doctor/jsx-no-undef": "error",
    "react-doctor/jsx-no-useless-fragment": "error",
    "react-doctor/jsx-numeric-and-leaked-render": "error",
    "react-doctor/jsx-pascal-case": "error",
    "react-doctor/jsx-props-no-spread-multi": "error",
    "react-doctor/jsx-props-no-spreading": "error",
    "react-doctor/jwt-insecure-verification": "error",
    "react-doctor/key-lifecycle-risk": "error",
    "react-doctor/label-has-associated-control": "error",
    "react-doctor/lang": "error",
    "react-doctor/loading-action-preserves-trigger": "error",
    "react-doctor/local-rpc-native-bridge-risk": "error",
    "react-doctor/mcp-tool-capability-risk": "error",
    "react-doctor/mdx-ssr-execution-risk": "error",
    "react-doctor/media-has-caption": "error",
    "react-doctor/mobx-no-make-auto-observable-in-inheritance": "error",
    "react-doctor/mobx-no-observer-wrapped-memo": "error",
    "react-doctor/mobx-reaction-disposer-discarded": "error",
    "react-doctor/motion-animate-presence-must-outlive-child": "error",
    "react-doctor/motion-animate-presence-requires-key": "error",
    "react-doctor/motion-animate-presence-wait-single-child": "error",
    "react-doctor/motion-create-in-render": "error",
    "react-doctor/motion-drag-axis-constraint-mismatch": "error",
    "react-doctor/motion-imperative-animation-in-render": "error",
    "react-doctor/motion-keyframe-times-mismatch": "error",
    "react-doctor/motion-layout-on-inline-element": "error",
    "react-doctor/motion-unstable-layout-id-in-iteration": "error",
    "react-doctor/motion-use-transform-range-length": "error",
    "react-doctor/motion-value-constructor-in-render": "error",
    "react-doctor/motion-value-subscription-in-render": "error",
    "react-doctor/mouse-events-have-key-events": "error",
    "react-doctor/nextjs-async-client-component": "error",
    "react-doctor/nextjs-async-dynamic-api-not-awaited": "error",
    "react-doctor/nextjs-error-boundary-missing-use-client": "error",
    "react-doctor/nextjs-global-error-missing-html-body": "error",
    "react-doctor/nextjs-image-missing-sizes": "error",
    "react-doctor/nextjs-inline-script-missing-id": "error",
    "react-doctor/nextjs-metadata-url-consistency": "error",
    "react-doctor/nextjs-missing-metadata": "error",
    "react-doctor/nextjs-no-a-element": "error",
    "react-doctor/nextjs-no-client-fetch-for-server-data": "error",
    "react-doctor/nextjs-no-client-side-redirect": "error",
    "react-doctor/nextjs-no-css-link": "error",
    "react-doctor/nextjs-no-default-export-in-route-handler": "error",
    "react-doctor/nextjs-no-edge-og-runtime": "error",
    "react-doctor/nextjs-no-font-link": "error",
    "react-doctor/nextjs-no-google-analytics-script": "error",
    "react-doctor/nextjs-no-head-import": "error",
    "react-doctor/nextjs-no-img-element": "error",
    "react-doctor/nextjs-no-native-script": "error",
    "react-doctor/nextjs-no-polyfill-script": "error",
    "react-doctor/nextjs-no-redirect-in-try-catch": "error",
    "react-doctor/nextjs-no-script-in-head": "error",
    "react-doctor/nextjs-no-side-effect-in-get-handler": "error",
    "react-doctor/nextjs-no-use-search-params-without-suspense": "error",
    "react-doctor/nextjs-no-vercel-og-import": "error",
    "react-doctor/no-access-key": "error",
    "react-doctor/no-adjust-state-on-prop-change": "error",
    "react-doctor/no-all-caps-body-text": "error",
    "react-doctor/no-arbitrary-px-font-size": "error",
    "react-doctor/no-aria-hidden-on-body": "error",
    "react-doctor/no-aria-hidden-on-focusable": "error",
    "react-doctor/no-aria-invalid-without-description": "error",
    "react-doctor/no-arithmetic-on-optional-chained-operand": "error",
    "react-doctor/no-array-find-result-member-access-without-guard": "error",
    "react-doctor/no-array-index-as-key": "error",
    "react-doctor/no-array-index-deref-without-bounds-or-empty-guard": "error",
    "react-doctor/no-array-index-key": "error",
    "react-doctor/no-assertive-status": "error",
    "react-doctor/no-async-effect-callback": "error",
    "react-doctor/no-async-event-handler-without-reentry-guard": "error",
    "react-doctor/no-auto-scrolling-content": "error",
    "react-doctor/no-autofocus": "error",
    "react-doctor/no-autoplay-without-muted": "error",
    "react-doctor/no-barrel-import": "error",
    "react-doctor/no-blocked-paste": "error",
    "react-doctor/no-boolean-toggle-without-functional-update": "error",
    "react-doctor/no-broken-image-source": "error",
    "react-doctor/no-call-component-as-function": "error",
    "react-doctor/no-cascading-set-state": "error",
    "react-doctor/no-chain-state-updates": "error",
    "react-doctor/no-children-prop": "error",
    "react-doctor/no-clipped-overlay": "error",
    "react-doctor/no-clone-element": "error",
    "react-doctor/no-collapse-request-error-to-empty-state": "error",
    "react-doctor/no-collapsed-literal-or-chain-as-value": "error",
    "react-doctor/no-common-root-font": "error",
    "react-doctor/no-conflicting-spring-options": "error",
    "react-doctor/no-controlled-input-value-without-state-update": "error",
    "react-doctor/no-controlled-selection-focus-effect": "error",
    "react-doctor/no-cramped-container-padding": "error",
    "react-doctor/no-create-context-in-render": "error",
    "react-doctor/no-create-object-url-in-render": "error",
    "react-doctor/no-create-object-url-without-revoke": "error",
    "react-doctor/no-create-ref-in-function-component": "error",
    "react-doctor/no-create-store-in-render": "error",
    "react-doctor/no-crushed-letter-spacing": "error",
    "react-doctor/no-danger": "error",
    "react-doctor/no-danger-with-children": "error",
    "react-doctor/no-dark-mode-glow": "error",
    "react-doctor/no-decorative-blur-orb": "error",
    "react-doctor/no-decorative-grid-background": "error",
    "react-doctor/no-decorative-pulse": "error",
    "react-doctor/no-decorative-radial-spotlight": "error",
    "react-doctor/no-default-props": "error",
    "react-doctor/no-default-purple-page-gradient": "error",
    "react-doctor/no-default-warm-page-surface": "error",
    "react-doctor/no-deprecated-keyboard-event-keycode-which": "error",
    "react-doctor/no-deprecated-tailwind-class": "error",
    "react-doctor/no-derived-state": "error",
    "react-doctor/no-derived-state-effect": "error",
    "react-doctor/no-derived-useState": "error",
    "react-doctor/no-did-mount-set-state": "error",
    "react-doctor/no-did-update-set-state": "error",
    "react-doctor/no-direct-mutation-state": "error",
    "react-doctor/no-direct-state-mutation": "error",
    "react-doctor/no-disabled-zoom": "error",
    "react-doctor/no-distracting-elements": "error",
    "react-doctor/no-document-start-view-transition": "error",
    "react-doctor/no-document-write": "error",
    "react-doctor/no-duplicate-static-id-reference": "error",
    "react-doctor/no-dynamic-import-path": "error",
    "react-doctor/no-dynamic-tailwind-class-fragment": "error",
    "react-doctor/no-eager-new-in-use-state-initializer": "error",
    "react-doctor/no-ease-in-motion": "error",
    "react-doctor/no-effect-chain": "error",
    "react-doctor/no-effect-event-handler": "error",
    "react-doctor/no-effect-event-in-deps": "error",
    "react-doctor/no-effect-with-fresh-deps": "error",
    "react-doctor/no-effect-wrapper-discards-callback-cleanup-return": "error",
    "react-doctor/no-emoji-heading-decoration": "error",
    "react-doctor/no-empty-card-shell": "error",
    "react-doctor/no-enter-submit-without-ime-composition-guard": "error",
    "react-doctor/no-eval": "error",
    "react-doctor/no-event-handler": "error",
    "react-doctor/no-event-trigger-state": "error",
    "react-doctor/no-excessive-card-surfaces": "error",
    "react-doctor/no-excessive-centered-copy": "error",
    "react-doctor/no-excessive-font-families": "error",
    "react-doctor/no-excessive-motion-stagger": "error",
    "react-doctor/no-excessive-pill-treatment": "error",
    "react-doctor/no-fake-browser-chrome": "error",
    "react-doctor/no-fetch-in-effect": "error",
    "react-doctor/no-fetch-response-used-without-status-check": "error",
    "react-doctor/no-fill-map-element-as-key": "error",
    "react-doctor/no-find-dom-node": "error",
    "react-doctor/no-fixed-inside-transformed-ancestor": "error",
    "react-doctor/no-flat-page-type-scale": "error",
    "react-doctor/no-floating-then-in-jsx-handler": "error",
    "react-doctor/no-flush-sync": "error",
    "react-doctor/no-focus-in-animation-completion-handler": "error",
    "react-doctor/no-focusable-content-in-aria-hidden": "error",
    "react-doctor/no-focusable-content-in-role-text": "error",
    "react-doctor/no-full-lodash-import": "error",
    "react-doctor/no-full-viewport-centered-hero": "error",
    "react-doctor/no-full-viewport-width": "error",
    "react-doctor/no-generic-handler-names": "error",
    "react-doctor/no-generic-marketing-copy": "error",
    "react-doctor/no-generic-purple-blue-icon-gradient": "error",
    "react-doctor/no-giant-component": "error",
    "react-doctor/no-global-css-variable-animation": "error",
    "react-doctor/no-gradient-text": "error",
    "react-doctor/no-gray-on-colored-background": "error",
    "react-doctor/no-hairline-border-wide-shadow": "error",
    "react-doctor/no-hero-eyebrow-chip": "error",
    "react-doctor/no-hover-only-reveal": "error",
    "react-doctor/no-hydration-branch-on-browser-global": "error",
    "react-doctor/no-icon-tile-heading-stack": "error",
    "react-doctor/no-image-hover-transform": "error",
    "react-doctor/no-img-lazy-with-high-fetchpriority": "error",
    "react-doctor/no-img-without-dimensions": "error",
    "react-doctor/no-impure-call-at-module-scope": "error",
    "react-doctor/no-impure-state-updater": "error",
    "react-doctor/no-indeterminate-attribute": "error",
    "react-doctor/no-inert-pointer-affordance": "error",
    "react-doctor/no-inert-sticky-position": "error",
    "react-doctor/no-initialize-state": "error",
    "react-doctor/no-inline-bounce-easing": "error",
    "react-doctor/no-inline-exhaustive-style": "error",
    "react-doctor/no-inline-hoc-on-component": "error",
    "react-doctor/no-inline-prop-on-memo-component": "error",
    "react-doctor/no-interactive-element-to-noninteractive-role": "error",
    "react-doctor/no-invalid-progress-range": "error",
    "react-doctor/no-invisible-focus-control": "error",
    "react-doctor/no-is-mounted": "error",
    "react-doctor/no-italic-serif-display-heading": "error",
    "react-doctor/no-json-parse-stringify-clone": "error",
    "react-doctor/no-jsx-element-type": "error",
    "react-doctor/no-justified-text": "error",
    "react-doctor/no-large-animated-blur": "error",
    "react-doctor/no-layout-property-animation": "error",
    "react-doctor/no-layout-shifting-interaction-state": "error",
    "react-doctor/no-layout-transition-inline": "error",
    "react-doctor/no-legacy-class-lifecycles": "error",
    "react-doctor/no-legacy-context-api": "error",
    "react-doctor/no-loading-flag-reset-outside-finally": "error",
    "react-doctor/no-locale-format-in-render": "error",
    "react-doctor/no-long-transition-duration": "error",
    "react-doctor/no-low-contrast-inline-style": "error",
    "react-doctor/no-manufactured-contrast-copy": "error",
    "react-doctor/no-many-boolean-props": "error",
    "react-doctor/no-match-media-in-state-initializer": "error",
    "react-doctor/no-mirror-prop-effect": "error",
    "react-doctor/no-mixed-animation-owners": "error",
    "react-doctor/no-mixed-icon-libraries": "error",
    "react-doctor/no-mixed-srcset-descriptors": "error",
    "react-doctor/no-moment": "error",
    "react-doctor/no-monotonous-page-spacing": "error",
    "react-doctor/no-multi-comp": "error",
    "react-doctor/no-multi-component-file": "error",
    "react-doctor/no-multiple-main-landmarks": "error",
    "react-doctor/no-multiple-unlabeled-navigation-landmarks": "error",
    "react-doctor/no-mutable-in-deps": "error",
    "react-doctor/no-mutate-queried-dom-node-in-component": "error",
    "react-doctor/no-mutate-then-set-or-return-same-reference": "error",
    "react-doctor/no-mutating-array-method-on-prop-or-hook-result": "error",
    "react-doctor/no-mutating-reducer-state": "error",
    "react-doctor/no-namespace": "error",
    "react-doctor/no-nested-card-surface": "error",
    "react-doctor/no-nested-component-definition": "error",
    "react-doctor/no-non-literal-selector-query-without-try-catch": "error",
    "react-doctor/no-non-null-assertion-on-maybe-undefined-result": "error",
    "react-doctor/no-nondeterministic-id-value-in-render-body": "error",
    "react-doctor/no-noninteractive-element-interactions": "error",
    "react-doctor/no-noninteractive-element-to-interactive-role": "error",
    "react-doctor/no-noninteractive-tabindex": "error",
    "react-doctor/no-nonresizable-textarea": "error",
    "react-doctor/no-nullish-coalescing-arithmetic-precedence": "error",
    "react-doctor/no-numbered-section-markers": "error",
    "react-doctor/no-object-keys-values-entries-on-maybe-undefined": "error",
    "react-doctor/no-object-or-array-coerced-to-string-in-template-literal": "error",
    "react-doctor/no-outline-none": "error",
    "react-doctor/no-overloaded-hover-state": "error",
    "react-doctor/no-oversized-long-heading": "error",
    "react-doctor/no-overwide-text-measure": "error",
    "react-doctor/no-pass-data-to-parent": "error",
    "react-doctor/no-pass-live-state-to-parent": "error",
    "react-doctor/no-passive-request-owner-ref": "error",
    "react-doctor/no-path-prefix-containment": "error",
    "react-doctor/no-permanent-will-change": "error",
    "react-doctor/no-pill-navigation-count": "error",
    "react-doctor/no-placeholder-only-field": "error",
    "react-doctor/no-placeholder-persona-copy": "error",
    "react-doctor/no-pointer-disabled-enabled-control": "error",
    "react-doctor/no-polymorphic-children": "error",
    "react-doctor/no-predicate-function-reference-in-boolean-position": "error",
    "react-doctor/no-presentation-role-conflict": "error",
    "react-doctor/no-prevent-default": "error",
    "react-doctor/no-promise-then-side-effect-in-effect-without-catch": "error",
    "react-doctor/no-prop-callback-in-effect": "error",
    "react-doctor/no-prop-callback-in-render": "error",
    "react-doctor/no-prop-types": "error",
    "react-doctor/no-pulsing-status-dot": "error",
    "react-doctor/no-pure-black-background": "error",
    "react-doctor/no-pure-black-shadow": "error",
    "react-doctor/no-radial-halo": "error",
    "react-doctor/no-random-key": "error",
    "react-doctor/no-react-children": "error",
    "react-doctor/no-react-dom-deprecated-apis": "error",
    "react-doctor/no-react19-deprecated-apis": "error",
    "react-doctor/no-reduced-motion-content-removal": "error",
    "react-doctor/no-redundant-display-class": "error",
    "react-doctor/no-redundant-roles": "error",
    "react-doctor/no-redundant-should-component-update": "error",
    "react-doctor/no-redundant-title-tooltip": "error",
    "react-doctor/no-ref-callback-cleanup-before-react-19": "error",
    "react-doctor/no-ref-current-in-render": "error",
    "react-doctor/no-render-in-render": "error",
    "react-doctor/no-render-prop-children": "error",
    "react-doctor/no-render-return-value": "error",
    "react-doctor/no-repeated-container-text": "error",
    "react-doctor/no-repeated-emoji-tiles": "error",
    "react-doctor/no-repeated-glass-surfaces": "error",
    "react-doctor/no-repeated-hover-scale": "error",
    "react-doctor/no-repeated-kicker-labels": "error",
    "react-doctor/no-repeated-placeholder-navigation": "error",
    "react-doctor/no-repeated-section-shells": "error",
    "react-doctor/no-repeating-gradient-decoration": "error",
    "react-doctor/no-reset-all-state-on-prop-change": "error",
    "react-doctor/no-responsive-hidden-accessible-name": "error",
    "react-doctor/no-scale-from-zero": "error",
    "react-doctor/no-secrets-in-client-code": "error",
    "react-doctor/no-self-updating-effect": "error",
    "react-doctor/no-server-side-image-map": "error",
    "react-doctor/no-set-state": "error",
    "react-doctor/no-set-state-after-await-in-effect": "error",
    "react-doctor/no-set-state-in-render": "error",
    "react-doctor/no-shape-assembled-illustration": "error",
    "react-doctor/no-side-effect-in-state-updater-function": "error",
    "react-doctor/no-side-tab-border": "error",
    "react-doctor/no-skipped-heading-level": "error",
    "react-doctor/no-small-form-control-text": "error",
    "react-doctor/no-smooth-scroll-without-reduced-motion": "error",
    "react-doctor/no-spread-accumulator-in-reduce": "error",
    "react-doctor/no-spread-props-over-defaults-clobbers-with-undefined": "error",
    "react-doctor/no-srcset-without-sizes": "error",
    "react-doctor/no-stale-timer-ref": "error",
    "react-doctor/no-static-element-interactions": "error",
    "react-doctor/no-static-motion-config-never": "error",
    "react-doctor/no-string-false-on-boolean-attribute": "error",
    "react-doctor/no-string-refs": "error",
    "react-doctor/no-svg-currentcolor-with-fill-class": "error",
    "react-doctor/no-symmetric-text-button-padding": "error",
    "react-doctor/no-sync-xhr": "error",
    "react-doctor/no-tailwind-layout-transition": "error",
    "react-doctor/no-this-in-sfc": "error",
    "react-doctor/no-tight-all-caps-heading": "error",
    "react-doctor/no-tight-body-leading": "error",
    "react-doctor/no-tight-display-tracking": "error",
    "react-doctor/no-tiny-text": "error",
    "react-doctor/no-tiny-uppercase-tracked-label": "error",
    "react-doctor/no-transition-all": "error",
    "react-doctor/no-transitioned-composite-widget-state": "error",
    "react-doctor/no-transitioned-focus-ring": "error",
    "react-doctor/no-unbounded-animation-frame-loop": "error",
    "react-doctor/no-uncontrolled-input": "error",
    "react-doctor/no-undeferred-third-party": "error",
    "react-doctor/no-undersized-icon-button": "error",
    "react-doctor/no-unescaped-dynamic-string-in-regexp": "error",
    "react-doctor/no-unescaped-entities": "error",
    "react-doctor/no-ungated-tailwind-animation": "error",
    "react-doctor/no-unguarded-browser-global-at-module-scope": "error",
    "react-doctor/no-unguarded-browser-global-in-render-or-hook-init": "error",
    "react-doctor/no-unguarded-numeric-input-parse": "error",
    "react-doctor/no-unguarded-throwing-parse-call": "error",
    "react-doctor/no-uniform-feature-card-grid": "error",
    "react-doctor/no-uninformative-aria-label": "error",
    "react-doctor/no-unknown-property": "error",
    "react-doctor/no-unowned-async-error-clear": "error",
    "react-doctor/no-unsafe": "error",
    "react-doctor/no-unsafe-json-parse": "error",
    "react-doctor/no-unstable-nested-components": "error",
    "react-doctor/no-unthrottled-scroll-mutation": "error",
    "react-doctor/no-uppercase-mono-label": "error",
    "react-doctor/no-uppercase-tracked-navigation-label": "error",
    "react-doctor/no-usememo-simple-expression": "error",
    "react-doctor/no-whole-object-default-losing-per-key-defaults": "error",
    "react-doctor/no-whole-object-dep-with-member-reads": "error",
    "react-doctor/no-wide-letter-spacing": "error",
    "react-doctor/no-will-update-set-state": "error",
    "react-doctor/no-z-index-9999": "error",
    "react-doctor/nosql-injection-risk": "error",
    "react-doctor/only-export-components": "error",
    "react-doctor/package-metadata-secret": "error",
    "react-doctor/path-traversal-risk": "error",
    "react-doctor/plugin-update-trust-risk": "error",
    "react-doctor/pointer-capture-needs-cancel-handler": "error",
    "react-doctor/postmessage-origin-risk": "error",
    "react-doctor/preact-no-children-length": "error",
    "react-doctor/preact-no-react-hooks-import": "error",
    "react-doctor/preact-no-render-arguments": "error",
    "react-doctor/preact-prefer-ondblclick": "error",
    "react-doctor/preact-prefer-oninput": "error",
    "react-doctor/prefer-dvh-over-vh": "error",
    "react-doctor/prefer-dynamic-import": "error",
    "react-doctor/prefer-es6-class": "error",
    "react-doctor/prefer-explicit-variants": "error",
    "react-doctor/prefer-function-component": "error",
    "react-doctor/prefer-html-dialog": "error",
    "react-doctor/prefer-module-scope-pure-function": "error",
    "react-doctor/prefer-module-scope-static-value": "error",
    "react-doctor/prefer-motion-transform-property": "error",
    "react-doctor/prefer-stable-empty-fallback": "error",
    "react-doctor/prefer-tabular-numeric-data": "error",
    "react-doctor/prefer-tag-over-role": "error",
    "react-doctor/prefer-truncate-shorthand": "error",
    "react-doctor/prefer-use-effect-event": "error",
    "react-doctor/prefer-use-sync-external-store": "error",
    "react-doctor/prefer-useReducer": "error",
    "react-doctor/public-debug-artifact": "error",
    "react-doctor/public-env-secret-name": "error",
    "react-doctor/query-destructure-result": "error",
    "react-doctor/query-floating-mutate-async": "error",
    "react-doctor/query-mutation-missing-invalidation": "error",
    "react-doctor/query-no-mutation-in-effect-as-read": "error",
    "react-doctor/query-no-query-in-effect": "error",
    "react-doctor/query-no-rest-destructuring": "error",
    "react-doctor/query-no-usequery-for-mutation": "error",
    "react-doctor/query-no-void-query-fn": "error",
    "react-doctor/query-stable-query-client": "error",
    "react-doctor/r3f-cap-device-pixel-ratio": "error",
    "react-doctor/r3f-limit-shadowed-point-lights": "error",
    "react-doctor/r3f-no-advancing-clock-in-use-frame": "error",
    "react-doctor/r3f-no-allocation-in-pointer-move": "error",
    "react-doctor/r3f-no-async-use-frame": "error",
    "react-doctor/r3f-no-clone-in-use-frame": "error",
    "react-doctor/r3f-no-compile-in-use-frame": "error",
    "react-doctor/r3f-no-deep-use-three-selector": "error",
    "react-doctor/r3f-no-dispose-loader-cache": "error",
    "react-doctor/r3f-no-duplicate-primitive-object": "error",
    "react-doctor/r3f-no-extend-in-render": "error",
    "react-doctor/r3f-no-extend-three-namespace": "error",
    "react-doctor/r3f-no-fresh-portal-container": "error",
    "react-doctor/r3f-no-fresh-use-three-selector": "error",
    "react-doctor/r3f-no-ignored-basic-material-properties": "error",
    "react-doctor/r3f-no-ignored-linewidth": "error",
    "react-doctor/r3f-no-imperative-attach-of-managed-ref": "error",
    "react-doctor/r3f-no-inline-primitive-object": "error",
    "react-doctor/r3f-no-inline-resource-prop": "error",
    "react-doctor/r3f-no-internal-imports": "error",
    "react-doctor/r3f-no-manual-canvas-resize": "error",
    "react-doctor/r3f-no-mutate-loader-cache": "error",
    "react-doctor/r3f-no-mutate-uniform-prop-source-in-use-frame": "error",
    "react-doctor/r3f-no-mutating-pointer-event-data": "error",
    "react-doctor/r3f-no-new-in-use-frame": "error",
    "react-doctor/r3f-no-normalized-float-buffer-attribute": "error",
    "react-doctor/r3f-no-null-loader-input": "error",
    "react-doctor/r3f-no-object-pointer-capture": "error",
    "react-doctor/r3f-no-recursive-raf-with-use-frame": "error",
    "react-doctor/r3f-no-shader-configuration-mutation-in-use-frame": "error",
    "react-doctor/r3f-no-shadows-on-unsupported-light": "error",
    "react-doctor/r3f-no-state-in-pointer-move": "error",
    "react-doctor/r3f-no-state-in-use-frame": "error",
    "react-doctor/r3f-no-sync-readback-in-use-frame": "error",
    "react-doctor/r3f-no-unstable-args": "error",
    "react-doctor/r3f-no-use-frame-dependency-array": "error",
    "react-doctor/r3f-prefer-gpu-instanced-animation": "error",
    "react-doctor/r3f-prefer-gpu-position-animation": "error",
    "react-doctor/r3f-prefer-instanced-mesh": "error",
    "react-doctor/r3f-prefer-use-loader": "error",
    "react-doctor/r3f-require-animation-mixer-update": "error",
    "react-doctor/r3f-require-data-texture-update": "error",
    "react-doctor/r3f-require-dynamic-buffer-usage": "error",
    "react-doctor/r3f-require-environment-for-metal": "error",
    "react-doctor/r3f-require-frame-delta": "error",
    "react-doctor/r3f-require-global-effect-cleanup": "error",
    "react-doctor/r3f-require-instanced-buffer-update": "error",
    "react-doctor/r3f-require-lighting-for-pbr": "error",
    "react-doctor/r3f-require-lit-material-normals": "error",
    "react-doctor/r3f-require-owned-texture-cleanup": "error",
    "react-doctor/r3f-require-position-buffer-update": "error",
    "react-doctor/r3f-require-projection-matrix-update": "error",
    "react-doctor/r3f-require-render-target-reset": "error",
    "react-doctor/r3f-require-render-with-positive-priority": "error",
    "react-doctor/r3f-require-root-unmount": "error",
    "react-doctor/r3f-require-shadows-enabled": "error",
    "react-doctor/r3f-require-transparent-for-opacity": "error",
    "react-doctor/r3f-require-uv-for-texture-map": "error",
    "react-doctor/r3f-texture-repeat-requires-wrapping": "error",
    "react-doctor/r3f-valid-buffer-attribute-array-length": "error",
    "react-doctor/r3f-valid-buffer-attribute-item-size": "error",
    "react-doctor/r3f-valid-fog-parameters": "error",
    "react-doctor/r3f-valid-material-opacity": "error",
    "react-doctor/r3f-valid-orthographic-camera": "error",
    "react-doctor/r3f-valid-pbr-material-properties": "error",
    "react-doctor/r3f-valid-perspective-camera": "error",
    "react-doctor/r3f-valid-physical-material-properties": "error",
    "react-doctor/r3f-valid-raycaster-range": "error",
    "react-doctor/r3f-valid-shadow-map-size": "error",
    "react-doctor/r3f-valid-spot-light-properties": "error",
    "react-doctor/r3f-valid-texture-color-space": "error",
    "react-doctor/r3f-webgpu-canvas-prop-compatibility": "error",
    "react-doctor/r3f-webgpu-no-gl-state": "error",
    "react-doctor/r3f-webgpu-no-high-precision-instancing": "error",
    "react-doctor/r3f-webgpu-no-js-uniform-branch": "error",
    "react-doctor/r3f-webgpu-no-legacy-effect-composer": "error",
    "react-doctor/r3f-webgpu-no-legacy-material-api": "error",
    "react-doctor/r3f-webgpu-no-unregistered-pipeline-pass": "error",
    "react-doctor/r3f-webgpu-require-async-init": "error",
    "react-doctor/radio-input-missing-name": "error",
    "react-doctor/raw-sql-injection-risk": "error",
    "react-doctor/react-compiler-no-manual-memoization": "error",
    "react-doctor/react-in-jsx-scope": "off",
    "react-doctor/react-markdown-unsanitized-raw-html": "error",
    "react-doctor/react-router-csp-nonce-consistency": "error",
    "react-doctor/react-router-descendant-routes-require-splat": "error",
    "react-doctor/react-router-guard-aborted-handle-error": "error",
    "react-doctor/react-router-internal-route-anchor": "error",
    "react-doctor/react-router-loader-fetch-forwards-signal": "error",
    "react-doctor/react-router-loader-parallel-fetch": "error",
    "react-doctor/react-router-nested-route-requires-outlet": "error",
    "react-doctor/react-router-no-catch-middleware-next": "error",
    "react-doctor/react-router-no-client-module-in-server-render": "error",
    "react-doctor/react-router-no-duplicate-route-id": "error",
    "react-doctor/react-router-no-empty-leaf-route": "error",
    "react-doctor/react-router-no-invalid-absolute-child-path": "error",
    "react-doctor/react-router-no-invalid-lazy-route-properties": "error",
    "react-doctor/react-router-no-invalid-splat-path": "error",
    "react-doctor/react-router-no-loader-request-body": "error",
    "react-doctor/react-router-no-middleware-response-body-consumption": "error",
    "react-doctor/react-router-no-multiple-blockers": "error",
    "react-doctor/react-router-no-multiple-middleware-next": "error",
    "react-doctor/react-router-no-multiple-set-search-params-in-tick": "error",
    "react-doctor/react-router-no-navigate-in-render": "error",
    "react-doctor/react-router-no-nested-router": "error",
    "react-doctor/react-router-no-redirect-in-try-catch": "error",
    "react-doctor/react-router-no-route-module-environment-suffix": "error",
    "react-doctor/react-router-no-router-in-render": "error",
    "react-doctor/react-router-no-session-mutation-in-loader": "error",
    "react-doctor/react-router-no-static-cookie-expires": "error",
    "react-doctor/react-router-no-unsynchronized-search-params-mutation": "error",
    "react-doctor/react-router-no-use-loader-data-in-error-ui": "error",
    "react-doctor/react-router-prefer-route-lazy": "error",
    "react-doctor/react-router-require-root-error-boundary": "error",
    "react-doctor/react-router-resource-link-requires-reload": "error",
    "react-doctor/react-router-return-navigation-promise-in-transition": "error",
    "react-doctor/react-router-server-middleware-return-response": "error",
    "react-doctor/react-router-session-mutation-requires-commit": "error",
    "react-doctor/react-router-v8-no-meta-data-field": "error",
    "react-doctor/react-router-v8-no-react-router-dom-import": "error",
    "react-doctor/react-router-v8-no-removed-future-flags": "error",
    "react-doctor/react-router-valid-route-object": "error",
    "react-doctor/redux-useselector-inline-derivation": "error",
    "react-doctor/redux-useselector-returns-new-collection": "error",
    "react-doctor/remotion-calculate-metadata-fetch-signal": "error",
    "react-doctor/remotion-deterministic-randomness": "error",
    "react-doctor/remotion-no-css-animation": "error",
    "react-doctor/remotion-no-css-transition": "error",
    "react-doctor/remotion-no-css-url-assets": "error",
    "react-doctor/remotion-no-module-scope-delay-render": "error",
    "react-doctor/remotion-no-native-media-elements": "error",
    "react-doctor/remotion-no-next-image": "error",
    "react-doctor/remotion-stable-delay-render-handle": "error",
    "react-doctor/rendering-animate-svg-wrapper": "error",
    "react-doctor/rendering-conditional-render": "error",
    "react-doctor/rendering-hoist-jsx": "error",
    "react-doctor/rendering-hydration-mismatch-time": "error",
    "react-doctor/rendering-hydration-no-flicker": "error",
    "react-doctor/rendering-script-defer-async": "error",
    "react-doctor/rendering-svg-precision": "error",
    "react-doctor/rendering-usetransition-loading": "error",
    "react-doctor/repository-secret-file": "error",
    "react-doctor/request-body-mass-assignment": "error",
    "react-doctor/require-autoplay-video-poster": "error",
    "react-doctor/require-render-return": "error",
    "react-doctor/require-scale-reveal-transform-origin": "error",
    "react-doctor/rerender-defer-reads-hook": "error",
    "react-doctor/rerender-dependencies": "error",
    "react-doctor/rerender-derived-state-from-hook": "error",
    "react-doctor/rerender-functional-setstate": "error",
    "react-doctor/rerender-lazy-ref-init": "error",
    "react-doctor/rerender-lazy-state-init": "error",
    "react-doctor/rerender-memo-before-early-return": "error",
    "react-doctor/rerender-memo-with-default-value": "error",
    "react-doctor/rerender-state-only-in-handlers": "error",
    "react-doctor/rerender-transitions-scroll": "error",
    "react-doctor/rn-animate-layout-property": "error",
    "react-doctor/rn-animation-reaction-as-derived": "error",
    "react-doctor/rn-bottom-sheet-no-ignored-scroll-prop": "error",
    "react-doctor/rn-bottom-sheet-no-state-in-on-animate": "error",
    "react-doctor/rn-bottom-sheet-prefer-native": "error",
    "react-doctor/rn-bottom-sheet-use-integrated-scrollable": "error",
    "react-doctor/rn-detox-missing-await": "error",
    "react-doctor/rn-list-callback-per-row": "error",
    "react-doctor/rn-list-data-mapped": "error",
    "react-doctor/rn-list-missing-estimated-item-size": "error",
    "react-doctor/rn-list-recyclable-without-types": "error",
    "react-doctor/rn-no-deep-imports": "error",
    "react-doctor/rn-no-deprecated-modules": "error",
    "react-doctor/rn-no-dimensions-get": "error",
    "react-doctor/rn-no-falsy-and-render": "error",
    "react-doctor/rn-no-image-children": "error",
    "react-doctor/rn-no-inline-flatlist-renderitem": "error",
    "react-doctor/rn-no-inline-object-in-list-item": "error",
    "react-doctor/rn-no-legacy-expo-packages": "error",
    "react-doctor/rn-no-legacy-shadow-styles": "error",
    "react-doctor/rn-no-non-native-navigator": "error",
    "react-doctor/rn-no-panresponder": "error",
    "react-doctor/rn-no-raw-text": "error",
    "react-doctor/rn-no-renderitem-key": "error",
    "react-doctor/rn-no-scroll-state": "error",
    "react-doctor/rn-no-scrollview-mapped-list": "error",
    "react-doctor/rn-no-set-native-props": "error",
    "react-doctor/rn-no-single-element-style-array": "error",
    "react-doctor/rn-platform-shaking-use-direct-import": "error",
    "react-doctor/rn-prefer-content-inset-adjustment": "error",
    "react-doctor/rn-prefer-expo-image": "error",
    "react-doctor/rn-prefer-pressable": "error",
    "react-doctor/rn-prefer-pressable-over-gesture-detector": "error",
    "react-doctor/rn-prefer-reanimated": "error",
    "react-doctor/rn-pressable-shared-value-mutation": "error",
    "react-doctor/rn-reanimated-4-no-legacy-spring-thresholds": "error",
    "react-doctor/rn-reanimated-4-no-removed-api": "error",
    "react-doctor/rn-reanimated-4-use-worklets-scheduler": "error",
    "react-doctor/rn-scrollview-dynamic-padding": "error",
    "react-doctor/rn-scrollview-flex-in-content-container": "error",
    "react-doctor/rn-style-prefer-boxshadow": "error",
    "react-doctor/role-button-requires-complete-keyboard-activation": "error",
    "react-doctor/role-has-required-aria-props": "error",
    "react-doctor/role-supports-aria-props": "error",
    "react-doctor/rules-of-hooks": "error",
    "react-doctor/scope": "error",
    "react-doctor/secret-in-fallback": "error",
    "react-doctor/self-closing-comp": "error",
    "react-doctor/server-after-nonblocking": "error",
    "react-doctor/server-auth-actions": "error",
    "react-doctor/server-cache-with-object-literal": "error",
    "react-doctor/server-dedup-props": "error",
    "react-doctor/server-fetch-without-revalidate": "error",
    "react-doctor/server-hoist-static-io": "error",
    "react-doctor/server-no-mutable-module-state": "error",
    "react-doctor/server-sequential-independent-await": "error",
    "react-doctor/shadcn-tabs-trigger-requires-list": "error",
    "react-doctor/state-in-constructor": "error",
    "react-doctor/style-prop-object": "error",
    "react-doctor/styled-components-duplicate-css-property-in-block": "error",
    "react-doctor/styled-components-non-transient-custom-prop-on-intrinsic-element": "error",
    "react-doctor/supabase-client-owned-authz-field": "error",
    "react-doctor/supabase-rls-policy-risk": "error",
    "react-doctor/supabase-table-missing-rls": "error",
    "react-doctor/svg-filter-clickjacking-risk": "error",
    "react-doctor/tabindex-no-positive": "error",
    "react-doctor/tanstack-start-get-mutation": "error",
    "react-doctor/tanstack-start-loader-parallel-fetch": "error",
    "react-doctor/tanstack-start-missing-head-content": "error",
    "react-doctor/tanstack-start-missing-scripts": "error",
    "react-doctor/tanstack-start-no-anchor-element": "error",
    "react-doctor/tanstack-start-no-direct-fetch-in-loader": "error",
    "react-doctor/tanstack-start-no-dynamic-server-fn-import": "error",
    "react-doctor/tanstack-start-no-navigate-in-render": "error",
    "react-doctor/tanstack-start-no-secrets-in-loader": "error",
    "react-doctor/tanstack-start-no-use-server-in-handler": "error",
    "react-doctor/tanstack-start-no-useeffect-fetch": "error",
    "react-doctor/tanstack-start-redirect-in-try-catch": "error",
    "react-doctor/tanstack-start-route-property-order": "error",
    "react-doctor/tanstack-start-server-fn-method-order": "error",
    "react-doctor/tanstack-start-server-fn-validate-input": "error",
    "react-doctor/tenant-static-proxy-risk": "error",
    "react-doctor/three-cap-device-pixel-ratio": "error",
    "react-doctor/three-effect-composer-output-pass-last": "error",
    "react-doctor/three-effect-composer-require-size-on-resize": "error",
    "react-doctor/three-gpu-computation-handle-init-error": "error",
    "react-doctor/three-gpu-computation-require-init-before-compute": "error",
    "react-doctor/three-gpu-computation-valid-variable-name": "error",
    "react-doctor/three-limit-shadowed-point-lights": "error",
    "react-doctor/three-no-allocation-in-pointer-move": "error",
    "react-doctor/three-no-async-animation-loop": "error",
    "react-doctor/three-no-clone-in-animation-loop": "error",
    "react-doctor/three-no-compile-in-animation-loop": "error",
    "react-doctor/three-no-ignored-basic-material-properties": "error",
    "react-doctor/three-no-ignored-linewidth": "error",
    "react-doctor/three-no-material-recompile-in-animation-loop": "error",
    "react-doctor/three-no-new-in-animation-loop": "error",
    "react-doctor/three-no-normalized-float-buffer-attribute": "error",
    "react-doctor/three-no-object-construction-in-render": "error",
    "react-doctor/three-no-redundant-uniforms-need-update": "error",
    "react-doctor/three-no-shader-configuration-mutation-in-animation-loop": "error",
    "react-doctor/three-no-shadows-on-unsupported-light": "error",
    "react-doctor/three-no-state-in-animation-loop": "error",
    "react-doctor/three-no-state-in-pointer-move": "error",
    "react-doctor/three-no-sync-readback-in-animation-loop": "error",
    "react-doctor/three-no-unconditional-renderer-resize-in-animation-loop": "error",
    "react-doctor/three-on-before-compile-require-program-cache-key": "error",
    "react-doctor/three-prefer-gpu-instanced-animation": "error",
    "react-doctor/three-prefer-gpu-position-animation": "error",
    "react-doctor/three-prefer-instanced-mesh": "error",
    "react-doctor/three-prefer-set-animation-loop": "error",
    "react-doctor/three-raw-shader-require-fragment-float-precision": "error",
    "react-doctor/three-raw-shader-require-glsl3-version": "error",
    "react-doctor/three-require-animation-mixer-cleanup": "error",
    "react-doctor/three-require-animation-mixer-update": "error",
    "react-doctor/three-require-camera-aspect-on-resize": "error",
    "react-doctor/three-require-controls-cleanup": "error",
    "react-doctor/three-require-controls-update": "error",
    "react-doctor/three-require-data-texture-update": "error",
    "react-doctor/three-require-dynamic-buffer-usage": "error",
    "react-doctor/three-require-environment-for-metal": "error",
    "react-doctor/three-require-frame-delta": "error",
    "react-doctor/three-require-gpu-computation-cleanup": "error",
    "react-doctor/three-require-instanced-buffer-update": "error",
    "react-doctor/three-require-ktx2-detect-support": "error",
    "react-doctor/three-require-lighting-for-pbr": "error",
    "react-doctor/three-require-lit-material-normals": "error",
    "react-doctor/three-require-loader-error-handling": "error",
    "react-doctor/three-require-owned-geometry-cleanup": "error",
    "react-doctor/three-require-owned-material-cleanup": "error",
    "react-doctor/three-require-owned-texture-cleanup": "error",
    "react-doctor/three-require-position-buffer-update": "error",
    "react-doctor/three-require-postprocessing-cleanup": "error",
    "react-doctor/three-require-projection-matrix-update": "error",
    "react-doctor/three-require-render-in-animation-loop": "error",
    "react-doctor/three-require-render-target-cleanup": "error",
    "react-doctor/three-require-render-target-reset": "error",
    "react-doctor/three-require-renderer-cleanup": "error",
    "react-doctor/three-require-renderer-dom-attachment": "error",
    "react-doctor/three-require-renderer-size": "error",
    "react-doctor/three-require-shadows-enabled": "error",
    "react-doctor/three-require-texture-update-after-wrapping-change": "error",
    "react-doctor/three-require-transparent-for-opacity": "error",
    "react-doctor/three-require-uv-for-texture-map": "error",
    "react-doctor/three-require-worker-loader-cleanup": "error",
    "react-doctor/three-shader-no-constant-out-of-bounds-index": "error",
    "react-doctor/three-shader-no-derivatives-in-nonuniform-flow": "error",
    "react-doctor/three-shader-no-glsl1-syntax-with-glsl3": "error",
    "react-doctor/three-shader-no-invalid-clamp-bounds": "error",
    "react-doctor/three-shader-no-invalid-constant-bit-operations": "error",
    "react-doctor/three-shader-no-invalid-constant-math": "error",
    "react-doctor/three-shader-no-invalid-smoothstep-edges": "error",
    "react-doctor/three-shader-no-inverse-of-uniform": "error",
    "react-doctor/three-shader-no-redeclared-builtins": "error",
    "react-doctor/three-shader-no-redundant-frag-depth": "error",
    "react-doctor/three-shader-no-reserved-identifiers": "error",
    "react-doctor/three-shader-no-version-directive": "error",
    "react-doctor/three-shader-prefer-small-integer-pow": "error",
    "react-doctor/three-shader-prefer-squared-distance-comparison": "error",
    "react-doctor/three-shader-require-compatible-uniform-values": "error",
    "react-doctor/three-shader-require-fragment-output-on-all-paths": "error",
    "react-doctor/three-shader-require-matching-uniforms": "error",
    "react-doctor/three-shader-require-matching-varyings": "error",
    "react-doctor/three-shader-require-position-on-all-paths": "error",
    "react-doctor/three-shader-require-uniform-bindings": "error",
    "react-doctor/three-shader-valid-global-initializers": "error",
    "react-doctor/three-shader-valid-uniform-definitions": "error",
    "react-doctor/three-texture-repeat-requires-wrapping": "error",
    "react-doctor/three-tsl-no-js-uniform-branch": "error",
    "react-doctor/three-valid-buffer-attribute-array-length": "error",
    "react-doctor/three-valid-buffer-attribute-item-size": "error",
    "react-doctor/three-valid-data-texture-data-length": "error",
    "react-doctor/three-valid-data-texture-dimensions": "error",
    "react-doctor/three-valid-fog-parameters": "error",
    "react-doctor/three-valid-gpu-computation-dimensions": "error",
    "react-doctor/three-valid-material-opacity": "error",
    "react-doctor/three-valid-orthographic-camera": "error",
    "react-doctor/three-valid-pbr-material-properties": "error",
    "react-doctor/three-valid-perspective-camera": "error",
    "react-doctor/three-valid-physical-material-properties": "error",
    "react-doctor/three-valid-raycaster-range": "error",
    "react-doctor/three-valid-shadow-map-size": "error",
    "react-doctor/three-valid-spot-light-properties": "error",
    "react-doctor/three-valid-texture-color-space": "error",
    "react-doctor/three-webgpu-no-high-precision-instancing": "error",
    "react-doctor/three-webgpu-no-legacy-effect-composer": "error",
    "react-doctor/three-webgpu-no-legacy-material-api": "error",
    "react-doctor/three-webgpu-require-init-before-sync-operation": "error",
    "react-doctor/unsafe-json-in-html": "error",
    "react-doctor/untrusted-redirect-following": "error",
    "react-doctor/url-prefilled-privileged-action": "error",
    "react-doctor/use-lazy-motion": "error",
    "react-doctor/valtio-no-proxy-read-in-render": "error",
    "react-doctor/valtio-no-snapshot-in-callback": "error",
    "react-doctor/void-dom-elements-no-children": "error",
    "react-doctor/waapi-animation-in-render": "error",
    "react-doctor/web-animation-offsets-valid": "error",
    "react-doctor/webgl-no-sync-readback-in-animation-loop": "error",
    "react-doctor/webhook-signature-risk": "error",
    "react-doctor/window-open-without-noopener": "error",
    "react-doctor/zod-v4-no-deprecated-error-apis": "error",
    "react-doctor/zod-v4-no-deprecated-error-customization": "error",
    "react-doctor/zod-v4-no-deprecated-schema-apis": "error",
    "react-doctor/zod-v4-prefer-top-level-string-formats": "error",
    "react-doctor/zustand-no-fresh-selector-result": "error",
    "react-doctor/zustand-no-get-during-initialization": "error",
    "react-doctor/zustand-no-mutating-state": "error",
    "react-doctor/zustand-no-whole-store-destructure": "error",
  },
  scope: "full",
  share: false,
  supplyChain: {
    enabled: false,
  },
  surfaces: {
    ciFailure: {
      includeFileContexts: ["test", "story"],
      includeTags: ["design"],
    },
    cli: {
      includeFileContexts: ["test", "story"],
      includeTags: ["design"],
    },
    prComment: {
      includeFileContexts: ["test", "story"],
      includeTags: ["design"],
    },
    score: {
      includeFileContexts: ["test", "story"],
      includeTags: ["design"],
    },
  },
  verbose: true,
  warnings: true,
});
