import { readFileSync } from "node:fs";
import { create, fromBinary } from "@bufbuild/protobuf";
import {
  CodeGeneratorRequestSchema,
  type CodeGeneratorResponse,
  CodeGeneratorResponse_Feature,
  FileDescriptorSetSchema,
} from "@bufbuild/protobuf/wkt";
import { expect, test } from "vitest";
import { pluginVersion, protocGenProtoform } from "./plugin.js";

const TRACER_ANNOTATIONS_PATTERN = /export const TracerExampleFormAnnotations = \{[\s\S]*?\n\} as const;/;

// The descriptor set is checked in; rebuild it from testdata/tracer.proto
// with `bun run testdata:build` after editing the fixture proto.
function runPluginOnTracerProto(): CodeGeneratorResponse {
  const bytes = readFileSync(new URL("./testdata/tracer.binpb", import.meta.url));
  const fileDescriptorSet = fromBinary(FileDescriptorSetSchema, bytes);
  const request = create(CodeGeneratorRequestSchema, {
    fileToGenerate: ["tracer.proto"],
    parameter: "target=ts,import_extension=js",
    protoFile: fileDescriptorSet.file,
  });
  return protocGenProtoform.run(request);
}

test("emits a _form.ts file matching the golden fixture", () => {
  const response = runPluginOnTracerProto();
  const formFile = response.file.find((file) => file.name === "tracer_form.ts");
  const golden = readFileSync(new URL("./__golden__/tracer_form.ts.golden", import.meta.url), "utf8");

  expect(formFile).toBeDefined();
  expect(formFile?.content).toContain(`@generated by protoc-gen-protoform v${pluginVersion}`);
  expect(formFile?.content).toBe(golden.replace("__PLUGIN_VERSION__", pluginVersion));
});

test("emits no files besides the form binding for the tracer proto", () => {
  const response = runPluginOnTracerProto();

  expect(response.file.map((file) => file.name)).toEqual(["tracer_form.ts"]);
});

test("emits source comments as registered form annotations", () => {
  const response = runPluginOnTracerProto();
  const formFile = response.file.find((file) => file.name === "tracer_form.ts");

  expect(formFile?.content).toContain('"protoform.test.v1.TracerExample": "A trace configuration example."');
  expect(formFile?.content).toContain('"protoform.test.v1.TracerExample.name": "The trace display name."');
  expect(formFile?.content).toContain("registerProtoAnnotations(TracerExampleSchema, TracerExampleFormAnnotations)");
  expect(formFile?.content).toContain("annotations: TracerExampleFormAnnotations");
  const tracerAnnotations = formFile?.content.match(TRACER_ANNOTATIONS_PATTERN)?.[0];
  expect(tracerAnnotations).toContain('"protoform.test.v1.TracerChild.detail": "A detail shown with the trace."');
});

test("declares support for proto3 optional fields", () => {
  const response = runPluginOnTracerProto();
  const proto3Optional = BigInt(CodeGeneratorResponse_Feature.PROTO3_OPTIONAL);

  // Bitwise operators are banned by lint, so test the feature bit
  // arithmetically: bit k is set iff (value / 2^k) % 2 === 1.
  expect((response.supportedFeatures / proto3Optional) % 2n).toBe(1n);
});
