// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  pages: [
    "bare-bones-form",
    "two-step-form",
    "deeply-nested",
    "cel-re2-form",
    "oneof-form",
    "server-error-form",
    "aip-resource-form",
    "kitchen-sink",
  ],
  title: "Przykłady",
};
