// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  pages: [
    "protobuf-v2-migration",
    "zod-migration",
    "yup-migration",
    "llm-migration-playbook",
  ],
  title: "Migracje",
};
