// Generated by scripts/generate-demo-catalog.ts.
'use client';

export const client = 'only';

import { formatSubmittedValue } from '../../lib/protobuf-provider';
import { useState } from 'react';

import {
  Alert,
  AlertDescription,
  AlertTitle,
} from '@/registry/base-nova/protoform/components/alert';
import { AutoForm } from '@/registry/base-nova/protoform/components/auto-form';
import { Badge } from '@/registry/base-nova/protoform/components/badge';
import { getDemoSchema } from '@/registry/base-nova/protoform/demo/runtime/demo-schemas';

export function Aip136CustomMethodsDemo() {
  const [submittedValue, setSubmittedValue] = useState<string>();
  const { defaultValues, schema } = getDemoSchema("provision-capacity");

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-2">
        <Badge variant="primary-inverted">React Hook Form</Badge>
        <Badge variant="outline">Live protobuf contract</Badge>
      </div>
      <p className="text-muted-foreground text-sm">
        {"Edit the focused request, submit it, and compare the live behavior with the executable compatibility evidence below."}
      </p>
      <AutoForm
        defaultValues={defaultValues}
        formOptions={{ mode: 'onBlur', reValidateMode: 'onChange' }}
        onFieldChange={() => setSubmittedValue(undefined)}
        onSubmit={(values) => setSubmittedValue(formatSubmittedValue(values))}
        schema={schema}
        withSubmit
      />
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription>
            <pre className="max-h-80 max-w-full overflow-auto whitespace-pre-wrap text-xs">
              {submittedValue}
            </pre>
          </AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default Aip136CustomMethodsDemo;
