// Generated by scripts/generate-demo-catalog.ts.
"use client";

export const client = "only";

import { useState } from "react";
import { Field as FinalField, Form as FinalForm } from "react-final-form";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Field, FieldError, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { EmailContractSchema } from "@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/conformance_pb";
import { createFinalFormValidator } from "../../lib/core";
import { createProtoFormSchema, formatSubmittedValue } from "../../lib/protobuf-provider";

interface EmailValues {
  email: string;
}

const schema = createProtoFormSchema<EmailValues, typeof EmailContractSchema>(EmailContractSchema);
const validate = createFinalFormValidator(schema);

export function FinalFormDemo() {
  const [submittedValue, setSubmittedValue] = useState<string>();

  return (
    <div className="space-y-6">
      <Badge variant="primary-inverted">Final Form interop</Badge>
      <FinalForm<EmailValues>
        initialValues={{ email: "" }}
        onSubmit={async (values) => {
          const result = await schema["~standard"].validate(values);
          if (!result.issues) {
            setSubmittedValue(formatSubmittedValue(result.value));
          }
        }}
        validate={validate}
      >
        {({ handleSubmit, submitting }) => (
          <form className="space-y-6" onSubmit={handleSubmit}>
            <FinalField<string> name="email">
              {({ input, meta }) => {
                const { name, onBlur: handleBlur, onChange: handleChange, onFocus: handleFocus, value } = input;
                const message =
                  (meta.touched || meta.submitFailed) && typeof meta.error === "string" ? meta.error : undefined;
                return (
                  <Field data-invalid={Boolean(message)}>
                    <FieldLabel htmlFor="final-form-email" required>
                      Email
                    </FieldLabel>
                    <Input
                      aria-invalid={Boolean(message) || undefined}
                      id="final-form-email"
                      name={name}
                      onBlur={handleBlur}
                      onChange={handleChange}
                      onFocus={handleFocus}
                      placeholder="ada@example.com"
                      type="email"
                      value={value}
                    />
                    <FieldError>{message}</FieldError>
                  </Field>
                );
              }}
            </FinalField>
            <Button isLoading={submitting} type="submit">
              Validate with Final Form
            </Button>
          </form>
        )}
      </FinalForm>
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription>
            <pre className="whitespace-pre-wrap text-xs">{submittedValue}</pre>
          </AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default FinalFormDemo;
