// Generated by scripts/generate-demo-catalog.ts.
"use client";

export const client = "only";

import { Formik } from "formik";
import { useState } from "react";
import { Alert, AlertDescription, AlertTitle } from "@/registry/base-nova/protoform/components/alert";
import { Badge } from "@/registry/base-nova/protoform/components/badge";
import { Button } from "@/registry/base-nova/protoform/components/button";
import { Field, FieldError, FieldLabel } from "@/registry/base-nova/protoform/components/field";
import { Input } from "@/registry/base-nova/protoform/components/input";
import { EmailContractSchema } from "@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/conformance_pb";
import { createFormikValidator } from "../../lib/core";
import { createProtoFormSchema, formatSubmittedValue } from "../../lib/protobuf-provider";

interface EmailValues {
  email: string;
}

const schema = createProtoFormSchema<EmailValues, typeof EmailContractSchema>(EmailContractSchema);
const validate = createFormikValidator(schema);

export function FormikDemo() {
  const [submittedValue, setSubmittedValue] = useState<string>();

  return (
    <div className="space-y-6">
      <Badge variant="primary-inverted">Formik interop</Badge>
      <Formik<EmailValues>
        initialValues={{ email: "" }}
        onSubmit={async (values) => {
          const result = await schema["~standard"].validate(values);
          if (!result.issues) {
            setSubmittedValue(formatSubmittedValue(result.value));
          }
        }}
        validate={validate}
      >
        {({ errors, handleBlur, handleChange, handleSubmit, isSubmitting, touched, values }) => {
          const message = touched.email && typeof errors.email === "string" ? errors.email : undefined;
          return (
            <form className="space-y-6" onSubmit={handleSubmit}>
              <Field data-invalid={Boolean(message)}>
                <FieldLabel htmlFor="formik-email" required>
                  Email
                </FieldLabel>
                <Input
                  aria-invalid={Boolean(message) || undefined}
                  id="formik-email"
                  name="email"
                  onBlur={handleBlur}
                  onChange={handleChange}
                  placeholder="ada@example.com"
                  type="email"
                  value={values.email}
                />
                <FieldError>{message}</FieldError>
              </Field>
              <Button isLoading={isSubmitting} type="submit">
                Validate with Formik
              </Button>
            </form>
          );
        }}
      </Formik>
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription>
            <pre className="whitespace-pre-wrap text-xs">{submittedValue}</pre>
          </AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default FormikDemo;
