// Generated by scripts/generate-demo-catalog.ts.
'use client';

export const client = 'only';

import { useState } from 'react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Field, FieldError, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { formatSubmittedValue } from '@/registry/base-nova/protoform/demo/runtime/format-submitted-value';
import { EmailContractSchema } from '@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/conformance_pb';
import { useProtoForm } from '@/registry/base-nova/protoform/hooks/use-proto-form-tanstack';

function errorMessage(error: unknown): string | undefined {
  if (typeof error === 'string') {
    return error;
  }
  if (error !== null && typeof error === 'object') {
    const message = Reflect.get(error, 'message');
    return typeof message === 'string' ? message : undefined;
  }
  return undefined;
}

export function TanstackFormDemo() {
  const [submittedValue, setSubmittedValue] = useState<string>();
  const [submissionError, setSubmissionError] = useState<string>();
  const form = useProtoForm(EmailContractSchema, {
    defaultValues: { email: '' },
    onSubmit: ({ value }) => {
      setSubmittedValue(formatSubmittedValue(form.createMessage(value)));
    },
  });

  return (
    <div className="space-y-6">
      <Badge variant="primary-inverted">TanStack Form interop</Badge>
      <form
        className="space-y-6"
        onSubmit={(event) => {
          event.preventDefault();
          event.stopPropagation();
          setSubmittedValue(undefined);
          setSubmissionError(undefined);
          form.handleSubmit().catch((error: unknown) => {
            const message = errorMessage(error);
            setSubmissionError(message !== undefined && message !== '' ? message : 'Submission failed. Try again.');
          });
        }}
      >
        <form.Field name="email">
          {(field) => {
            const messages = field.state.meta.errors
              .map(errorMessage)
              .filter((message): message is string => Boolean(message));
            const invalid = messages.length > 0;
            return (
              <Field data-invalid={invalid}>
                <FieldLabel htmlFor={field.name} required>
                  Email
                </FieldLabel>
                <Input
                  aria-invalid={invalid || undefined}
                  id={field.name}
                  name={field.name}
                  onBlur={field.handleBlur}
                  onChange={(event) => field.handleChange(event.target.value)}
                  placeholder="ada@example.com"
                  type="email"
                  value={field.state.value}
                />
                <FieldError>{messages.join('\n')}</FieldError>
              </Field>
            );
          }}
        </form.Field>
        <Button type="submit">Validate with TanStack Form</Button>
      </form>
      {submissionError ? (
        <Alert role="alert" variant="destructive">
          <AlertTitle>Submission failed</AlertTitle>
          <AlertDescription>{submissionError}</AlertDescription>
        </Alert>
      ) : null}
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription>
            <pre className="whitespace-pre-wrap text-xs">{submittedValue}</pre>
          </AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default TanstackFormDemo;
