// Generated by scripts/generate-demo-catalog.ts.
'use client';

export const client = 'only';

import { formatSubmittedValue } from '../../lib/protobuf-provider';
import { useState } from 'react';

import { Alert, AlertDescription, AlertTitle } from '@/registry/base-nova/protoform/components/alert';
import { Badge } from '@/registry/base-nova/protoform/components/badge';
import { Button } from '@/registry/base-nova/protoform/components/button';
import { Field, FieldError, FieldLabel } from '@/registry/base-nova/protoform/components/field';
import { Input } from '@/registry/base-nova/protoform/components/input';
import { useProtoForm } from '@/registry/base-nova/protoform/hooks/use-proto-form-tanstack';
import { EmailContractSchema } from '@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/conformance_pb';

function errorMessage(error: unknown): string | undefined {
  if (typeof error === 'string') {
    return error;
  }
  if (error && typeof error === 'object') {
    const message = Reflect.get(error, 'message');
    return typeof message === 'string' ? message : undefined;
  }
  return;
}

export function TanstackFormDemo() {
  const [submittedValue, setSubmittedValue] = useState<string>();
  const form = useProtoForm(EmailContractSchema, {
    defaultValues: { email: '' },
    onSubmit: ({ value }) => {
      setSubmittedValue(formatSubmittedValue(form.createMessage(value)));
    },
  });

  return (
    <div className="space-y-6">
      <Badge variant="primary-inverted">TanStack Form interop</Badge>
      <form
        className="space-y-6"
        onSubmit={(event) => {
          event.preventDefault();
          event.stopPropagation();
          form.handleSubmit();
        }}
      >
        <form.Field name="email">
          {(field) => {
            const messages = field.state.meta.errors.map(errorMessage).filter((message): message is string => Boolean(message));
            const invalid = messages.length > 0;
            return (
              <Field data-invalid={invalid}>
                <FieldLabel htmlFor={field.name} required>Email</FieldLabel>
                <Input
                  aria-invalid={invalid || undefined}
                  id={field.name}
                  name={field.name}
                  onBlur={field.handleBlur}
                  onChange={(event) => field.handleChange(event.target.value)}
                  placeholder="ada@example.com"
                  type="email"
                  value={field.state.value}
                />
                <FieldError>{messages.join('\n')}</FieldError>
              </Field>
            );
          }}
        </form.Field>
        <Button type="submit">Validate with TanStack Form</Button>
      </form>
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription><pre className="whitespace-pre-wrap text-xs">{submittedValue}</pre></AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default TanstackFormDemo;
