// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  pages: ["protobuf", "protovalidate", "cel", "production"],
  title: "功能範例",
};
