// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  pages: ["api-recipes", "standard-schema", "protovalidate", "cel-expressions", "server-errors", "aip-protobuf"],
  title: "验证与 API",
};
