import { execFileSync } from "node:child_process";
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";

import {
  type DemoCatalogEntry,
  demoCatalog,
} from "../examples/catalog/demo-catalog.js";
import { demoHubs, demosForHub } from "../examples/catalog/demo-docs.js";

const root = new URL("../", import.meta.url).pathname;
const aipDirectory = join(root, "content/docs/(aip-examples)");
const featureDirectory = join(root, "content/docs/(feature-examples)");
const registryDemoDirectory = join(
  root,
  "registry/base-nova/protoform/demo/catalog"
);
const registryRuntimeDirectory = join(
  root,
  "registry/base-nova/protoform/demo/runtime"
);

const generatedHeader =
  "{/* Generated by scripts/generate-demo-catalog.ts. */}";
const generatedSourceHeader =
  "// Generated by scripts/generate-demo-catalog.ts.";

function assertNever(value: never): never {
  throw new Error(`Unhandled value: ${String(value)}`);
}

function write(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${content.trim()}\n`);
}

function removeGeneratedFiles(directory: string, extension: string): void {
  mkdirSync(directory, { recursive: true });
  for (const file of readdirSync(directory)) {
    const path = join(directory, file);
    if (
      file.endsWith(extension) &&
      readFileSync(path, "utf8").includes("generate-demo-catalog.ts")
    ) {
      unlinkSync(path);
    }
  }
}

function meta(title: string, pages: readonly string[]): string {
  const pageList = pages.map((page) => JSON.stringify(page)).join(", ");

  return `import { defineMeta } from "blume";

export default defineMeta({
  pages: [${pageList}],
  title: ${JSON.stringify(title)},
});`;
}

function registryItem(name: string): string {
  return `@protoform/${name}`;
}

const seoDescriptionSuffixes = [
  " Learn more.",
  " See the practical Protoform implementation guide.",
  " See practical Protoform implementation guidance for production use.",
  " Learn how to apply this contract with practical Protoform implementation guidance for production use.",
] as const;

function seoDescription(description: string): string {
  if (description.length >= 110 && description.length <= 160) {
    return description;
  }

  const expanded = seoDescriptionSuffixes
    .map((suffix) => `${description}${suffix}`)
    .find((candidate) => candidate.length >= 110 && candidate.length <= 160);

  if (!expanded) {
    throw new Error(
      `Could not create a 110–160 character SEO description from: ${description}`
    );
  }

  return expanded;
}

function hubPage(title: string, description: string, category: string): string {
  return `---
title: ${JSON.stringify(title)}
description: ${JSON.stringify(seoDescription(description))}
---

${generatedHeader}

Choose a focused live demo. Each selection has a stable deep link and an independent registry install.

Use the filters and deep links below to isolate one contract at a time. Each demo keeps its schema,
form engine, registry item, and executable evidence visible so you can compare behavior before
copying code. Start with the smallest relevant example, exercise its values and failure paths, then
follow the installation and evidence links to reproduce the same behavior in your application.

<DemoHub category="${category}" />
`;
}

function wrapperName(slug: string): string {
  return `${slug
    .split("-")
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("")}Demo`;
}

function tanStackRegistryWrapper(): string {
  return `${generatedSourceHeader}
'use client';

export const client = 'only';

import { formatSubmittedValue } from '../../lib/protobuf-provider';
import { useState } from 'react';

import { Alert, AlertDescription, AlertTitle } from '@/registry/base-nova/protoform/components/alert';
import { Badge } from '@/registry/base-nova/protoform/components/badge';
import { Button } from '@/registry/base-nova/protoform/components/button';
import { Field, FieldError, FieldLabel } from '@/registry/base-nova/protoform/components/field';
import { Input } from '@/registry/base-nova/protoform/components/input';
import { useProtoForm } from '@/registry/base-nova/protoform/hooks/use-proto-form-tanstack';
import { EmailContractSchema } from '@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/conformance_pb';

function errorMessage(error: unknown): string | undefined {
  if (typeof error === 'string') {
    return error;
  }
  if (error && typeof error === 'object') {
    const message = Reflect.get(error, 'message');
    return typeof message === 'string' ? message : undefined;
  }
  return;
}

export function TanstackFormDemo() {
  const [submittedValue, setSubmittedValue] = useState<string>();
  const form = useProtoForm(EmailContractSchema, {
    defaultValues: { email: '' },
    onSubmit: ({ value }) => {
      setSubmittedValue(formatSubmittedValue(form.createMessage(value)));
    },
  });

  return (
    <div className="space-y-6">
      <Badge variant="primary-inverted">TanStack Form interop</Badge>
      <form
        className="space-y-6"
        onSubmit={(event) => {
          event.preventDefault();
          event.stopPropagation();
          form.handleSubmit();
        }}
      >
        <form.Field name="email">
          {(field) => {
            const messages = field.state.meta.errors.map(errorMessage).filter((message): message is string => Boolean(message));
            const invalid = messages.length > 0;
            return (
              <Field data-invalid={invalid}>
                <FieldLabel htmlFor={field.name} required>Email</FieldLabel>
                <Input
                  aria-invalid={invalid || undefined}
                  id={field.name}
                  name={field.name}
                  onBlur={field.handleBlur}
                  onChange={(event) => field.handleChange(event.target.value)}
                  placeholder="ada@example.com"
                  type="email"
                  value={field.state.value}
                />
                <FieldError>{messages.join('\\n')}</FieldError>
              </Field>
            );
          }}
        </form.Field>
        <Button type="submit">Validate with TanStack Form</Button>
      </form>
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription><pre className="whitespace-pre-wrap text-xs">{submittedValue}</pre></AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default TanstackFormDemo;`;
}

function formikRegistryWrapper(): string {
  return `${generatedSourceHeader}
'use client';

export const client = 'only';

import { createFormikValidator } from '../../lib/core';
import { createProtoFormSchema, formatSubmittedValue } from '../../lib/protobuf-provider';
import { Formik } from "formik";
import { useState } from 'react';

import { Alert, AlertDescription, AlertTitle } from '@/registry/base-nova/protoform/components/alert';
import { Badge } from '@/registry/base-nova/protoform/components/badge';
import { Button } from '@/registry/base-nova/protoform/components/button';
import { Field, FieldError, FieldLabel } from '@/registry/base-nova/protoform/components/field';
import { Input } from '@/registry/base-nova/protoform/components/input';
import { EmailContractSchema } from '@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/conformance_pb';

interface EmailValues {
  email: string;
}

const schema = createProtoFormSchema<EmailValues, typeof EmailContractSchema>(EmailContractSchema);
const validate = createFormikValidator(schema);

export function FormikDemo() {
  const [submittedValue, setSubmittedValue] = useState<string>();

  return (
    <div className="space-y-6">
      <Badge variant="primary-inverted">Formik interop</Badge>
      <Formik<EmailValues>
        initialValues={{ email: '' }}
        onSubmit={async (values) => {
          const result = await schema['~standard'].validate(values);
          if (!result.issues) {
            setSubmittedValue(formatSubmittedValue(result.value));
          }
        }}
        validate={validate}
      >
        {({ errors, handleBlur, handleChange, handleSubmit, isSubmitting, touched, values }) => {
          const message = touched.email && typeof errors.email === 'string' ? errors.email : undefined;
          return (
            <form className="space-y-6" onSubmit={handleSubmit}>
              <Field data-invalid={Boolean(message)}>
                <FieldLabel htmlFor="formik-email" required>Email</FieldLabel>
                <Input
                  aria-invalid={Boolean(message) || undefined}
                  id="formik-email"
                  name="email"
                  onBlur={handleBlur}
                  onChange={handleChange}
                  placeholder="ada@example.com"
                  type="email"
                  value={values.email}
                />
                <FieldError>{message}</FieldError>
              </Field>
              <Button isLoading={isSubmitting} type="submit">Validate with Formik</Button>
            </form>
          );
        }}
      </Formik>
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription><pre className="whitespace-pre-wrap text-xs">{submittedValue}</pre></AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default FormikDemo;`;
}

function finalFormRegistryWrapper(): string {
  return `${generatedSourceHeader}
'use client';

export const client = 'only';

import { createFinalFormValidator } from '../../lib/core';
import { createProtoFormSchema, formatSubmittedValue } from '../../lib/protobuf-provider';
import { useState } from 'react';
import { Field as FinalField, Form as FinalForm } from "react-final-form";

import { Alert, AlertDescription, AlertTitle } from '@/registry/base-nova/protoform/components/alert';
import { Badge } from '@/registry/base-nova/protoform/components/badge';
import { Button } from '@/registry/base-nova/protoform/components/button';
import { Field, FieldError, FieldLabel } from '@/registry/base-nova/protoform/components/field';
import { Input } from '@/registry/base-nova/protoform/components/input';
import { EmailContractSchema } from '@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/conformance_pb';

interface EmailValues {
  email: string;
}

const schema = createProtoFormSchema<EmailValues, typeof EmailContractSchema>(EmailContractSchema);
const validate = createFinalFormValidator(schema);

export function FinalFormDemo() {
  const [submittedValue, setSubmittedValue] = useState<string>();

  return (
    <div className="space-y-6">
      <Badge variant="primary-inverted">Final Form interop</Badge>
      <FinalForm<EmailValues>
        initialValues={{ email: '' }}
        onSubmit={async (values) => {
          const result = await schema['~standard'].validate(values);
          if (!result.issues) {
            setSubmittedValue(formatSubmittedValue(result.value));
          }
        }}
        validate={validate}
      >
        {({ handleSubmit, submitting }) => (
          <form className="space-y-6" onSubmit={handleSubmit}>
            <FinalField<string> name="email">
              {({ input, meta }) => {
                const message = (meta.touched || meta.submitFailed) && typeof meta.error === 'string' ? meta.error : undefined;
                return (
                  <Field data-invalid={Boolean(message)}>
                    <FieldLabel htmlFor="final-form-email" required>Email</FieldLabel>
                    <Input
                      {...input}
                      aria-invalid={Boolean(message) || undefined}
                      id="final-form-email"
                      placeholder="ada@example.com"
                      type="email"
                    />
                    <FieldError>{message}</FieldError>
                  </Field>
                );
              }}
            </FinalField>
            <Button isLoading={submitting} type="submit">Validate with Final Form</Button>
          </form>
        )}
      </FinalForm>
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription><pre className="whitespace-pre-wrap text-xs">{submittedValue}</pre></AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default FinalFormDemo;`;
}

function reactHookFormRegistryWrapper(demo: DemoCatalogEntry): string {
  const methodImport =
    demo.slug === "bufbuild-descriptors"
      ? "\nimport { LibraryService } from '@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/aip_pb';\n"
      : "";
  const methodDeclaration =
    demo.slug === "bufbuild-descriptors"
      ? "\nconst method = LibraryService.method.createBook;\n"
      : "";
  const schemaDeclaration =
    demo.slug === "bufbuild-descriptors"
      ? `  const { defaultValues } = getDemoSchema(${JSON.stringify(demo.schemaKey)});
  const schema = method.input;`
      : `  const { defaultValues, schema } = getDemoSchema(${JSON.stringify(demo.schemaKey)});`;
  const methodBadge =
    demo.slug === "bufbuild-descriptors"
      ? '\n        <Badge variant="outline">{method.methodKind} RPC</Badge>'
      : "";
  const methodShape =
    demo.slug === "bufbuild-descriptors"
      ? `
      <div
        aria-label="RPC method shape"
        className="grid gap-3 rounded-lg border border-border bg-muted/30 p-4 text-sm sm:grid-cols-2"
      >
        <div>
          <p className="font-medium text-foreground">{method.name}</p>
          <p className="text-muted-foreground">Generated method descriptor</p>
        </div>
        <dl className="grid gap-2">
          <div>
            <dt className="font-medium text-foreground">Input</dt>
            <dd className="break-all text-muted-foreground">
              {method.input.typeName}
            </dd>
          </div>
          <div>
            <dt className="font-medium text-foreground">Output</dt>
            <dd className="break-all text-muted-foreground">
              {method.output.typeName}
            </dd>
          </div>
        </dl>
      </div>`
      : "";

  return `${generatedSourceHeader}
'use client';

export const client = 'only';

import { formatSubmittedValue } from '../../lib/protobuf-provider';
import { useState } from 'react';

import {
  Alert,
  AlertDescription,
  AlertTitle,
} from '@/registry/base-nova/protoform/components/alert';
import { AutoForm } from '@/registry/base-nova/protoform/components/auto-form';
import { Badge } from '@/registry/base-nova/protoform/components/badge';
import { getDemoSchema } from '@/registry/base-nova/protoform/demo/runtime/demo-schemas';
${methodImport}${methodDeclaration}
export function ${wrapperName(demo.slug)}() {
  const [submittedValue, setSubmittedValue] = useState<string>();
${schemaDeclaration}

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-2">
        <Badge variant="primary-inverted">React Hook Form</Badge>
        <Badge variant="outline">Live protobuf contract</Badge>${methodBadge}
      </div>${methodShape}
      <p className="text-muted-foreground text-sm">
        {${JSON.stringify(demo.tryIt)}}
      </p>
      <AutoForm
        defaultValues={defaultValues}
        formOptions={{ mode: 'onBlur', reValidateMode: 'onChange' }}
        onFieldChange={() => setSubmittedValue(undefined)}
        onSubmit={(values) => setSubmittedValue(formatSubmittedValue(values))}
        schema={schema}
        withSubmit
      />
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription>
            <pre className="max-h-80 max-w-full overflow-auto whitespace-pre-wrap text-xs">
              {submittedValue}
            </pre>
          </AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default ${wrapperName(demo.slug)};`;
}

function registryWrapper(demo: DemoCatalogEntry): string {
  if (demo.engine === "tanstack-form") {
    return tanStackRegistryWrapper();
  }
  if (demo.engine === "formik") {
    return formikRegistryWrapper();
  }
  if (demo.engine === "final-form") {
    return finalFormRegistryWrapper();
  }
  return reactHookFormRegistryWrapper(demo);
}

function dependenciesForDemo(demo: DemoCatalogEntry): string[] {
  switch (demo.engine) {
    case "formik":
      return ["formik"];
    case "final-form":
      return ["final-form", "react-final-form"];
    case "tanstack-form":
      return ["@tanstack/react-form"];
    case "react-hook-form":
      return [];
    default:
      return assertNever(demo.engine);
  }
}

function generateDocs(): void {
  removeGeneratedFiles(aipDirectory, ".mdx");
  const aipHub = demoHubs.find((hub) => hub.category === "aip");
  if (!aipHub) {
    throw new Error("Missing AIP demo hub definition.");
  }
  write(
    join(aipDirectory, "aip-example-catalog.mdx"),
    hubPage(aipHub.title, aipHub.description, aipHub.category)
  );
  write(
    join(aipDirectory, "meta.ts"),
    meta("AIP examples", ["aip-example-catalog"])
  );

  const featureCategories = [
    ["protobuf", "Protobuf"],
    ["protovalidate", "Protovalidate"],
    ["cel", "CEL"],
    ["production", "Production and interoperability"],
  ] as const;
  removeGeneratedFiles(featureDirectory, ".mdx");
  write(
    join(featureDirectory, "meta.ts"),
    meta(
      "Feature examples",
      featureCategories.map(([category]) => category)
    )
  );

  for (const [category, title] of featureCategories) {
    const directory = join(featureDirectory, `(${category})`);
    removeGeneratedFiles(directory, ".mdx");
    const hub = demoHubs.find((candidate) => candidate.category === category);
    if (!hub || demosForHub(hub.category).length === 0) {
      throw new Error(`Missing populated ${title} demo hub definition.`);
    }
    write(
      join(directory, `${hub.slug}.mdx`),
      hubPage(hub.title, hub.description, hub.category)
    );
    write(join(directory, "meta.ts"), meta(title, [hub.slug]));
  }
}

function generateRegistryRuntime(): string[] {
  const generatedFiles = [
    "buf/validate/validate_pb.ts",
    "google/api/annotations_pb.ts",
    "google/api/client_pb.ts",
    "google/api/field_behavior_pb.ts",
    "google/api/field_info_pb.ts",
    "google/api/http_pb.ts",
    "google/api/launch_stage_pb.ts",
    "google/api/resource_pb.ts",
    "google/rpc/status_pb.ts",
    "protoform/conformance/v1/aip_form.ts",
    "protoform/conformance/v1/aip_pb.ts",
    "protoform/conformance/v1/conformance_pb.ts",
    "protoform/conformance/v1/editions_2024_pb.ts",
    "protoform/conformance/v1/editions_pb.ts",
    "protoform/conformance/v1/predefined_pb.ts",
  ];

  for (const file of generatedFiles) {
    const target = join(registryRuntimeDirectory, "gen", file);
    write(target, readFileSync(join(root, "conformance/gen", file), "utf8"));
  }

  const schemaKeys = [
    ...new Set(demoCatalog.map((demo) => demo.schemaKey)),
  ].toSorted();
  const schemaType = `export type DemoSchemaKey =\n${schemaKeys
    .map((key) => `  | ${JSON.stringify(key)}`)
    .join("\n")};`;
  const schemaSource = readFileSync(
    join(root, "examples/catalog/demo-schemas.ts"),
    "utf8"
  )
    .replaceAll(
      "../../conformance/gen/protoform/conformance/v1/",
      "./gen/protoform/conformance/v1/"
    )
    .replace(
      'import type { DemoSchemaKey } from "./demo-catalog.js";',
      schemaType
    );
  write(join(registryRuntimeDirectory, "demo-schemas.ts"), schemaSource);

  return [
    "registry/base-nova/protoform/demo/runtime/demo-schemas.ts",
    ...generatedFiles.map(
      (file) => `registry/base-nova/protoform/demo/runtime/gen/${file}`
    ),
  ];
}

function generateRegistry(): void {
  removeGeneratedFiles(registryDemoDirectory, ".tsx");
  for (const demo of demoCatalog) {
    write(
      join(registryDemoDirectory, `${demo.slug}.tsx`),
      registryWrapper(demo)
    );
  }

  const runtimeFiles = generateRegistryRuntime();
  const registryPath = join(root, "registry.json");
  const registry = JSON.parse(readFileSync(registryPath, "utf8")) as {
    items: Array<Record<string, unknown> & { name: string }>;
  };
  const generatedNames = new Set([
    "protoform-demo-runtime",
    ...demoCatalog.map((demo) => demo.registryName),
  ]);
  const items = registry.items.filter((item) => {
    if (generatedNames.has(item.name)) {
      return false;
    }
    const files = Array.isArray(item.files) ? item.files : [];
    return !files.some(
      (file) =>
        typeof file === "object" &&
        file !== null &&
        "path" in file &&
        typeof file.path === "string" &&
        file.path.includes("/protoform/demo/catalog/")
    );
  });
  const umbrella = items.find((item) => item.name === "protoform-examples");
  if (!umbrella) {
    throw new Error("registry.json is missing protoform-examples");
  }
  umbrella.registryDependencies = [
    registryItem("protoform"),
    ...demoCatalog.map((demo) => registryItem(demo.registryName)),
  ];

  items.push({
    dependencies: ["@bufbuild/protobuf", "react", "react-hook-form"],
    description:
      "Shared fixture descriptors and generated compatibility contracts for focused Protoform demos.",
    files: runtimeFiles.map((path) => ({
      path,
      target: `~/components/protoform-examples/runtime/${path.replace(
        "registry/base-nova/protoform/demo/runtime/",
        ""
      )}`,
      type: path.endsWith(".tsx") ? "registry:component" : "registry:lib",
    })),
    name: "protoform-demo-runtime",
    registryDependencies: [registryItem("protoform")],
    title: "Protoform demo runtime",
    type: "registry:block",
  });
  items.push(
    ...demoCatalog.map((demo) => {
      const registryDependencies = [registryItem("protoform-demo-runtime")];
      if (demo.engine === "tanstack-form") {
        registryDependencies.push(registryItem("use-proto-form-tanstack"));
      }

      return {
        dependencies: dependenciesForDemo(demo),
        description: demo.description,
        files: [
          {
            path: `registry/base-nova/protoform/demo/catalog/${demo.slug}.tsx`,
            target: `~/components/protoform-examples/${demo.slug}.tsx`,
            type: "registry:component",
          },
        ],
        name: demo.registryName,
        registryDependencies,
        title: demo.title,
        type: "registry:example",
      };
    })
  );
  registry.items = items;
  writeFileSync(registryPath, `${JSON.stringify(registry, null, 2)}\n`);
  execFileSync("bunx", ["biome", "format", registryPath, "--write"], {
    cwd: root,
    stdio: "ignore",
  });
}

generateDocs();
generateRegistry();
