import { execFileSync } from "node:child_process";
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";

import {
  type DemoCatalogEntry,
  demoCatalog,
} from "../examples/catalog/demo-catalog.js";
import { readinessRequirements } from "../readiness/profile.js";

const root = new URL("../", import.meta.url).pathname;
const aipDirectory = join(root, "content/docs/(aip-examples)");
const featureDirectory = join(root, "content/docs/(feature-examples)");
const registryDemoDirectory = join(
  root,
  "registry/base-nova/protoform/demo/catalog"
);
const registryRuntimeDirectory = join(
  root,
  "registry/base-nova/protoform/demo/runtime"
);

const generatedHeader =
  "{/* Generated by scripts/generate-demo-catalog.ts. */}";
const generatedSourceHeader =
  "// Generated by scripts/generate-demo-catalog.ts.";

function assertNever(value: never): never {
  throw new Error(`Unhandled value: ${String(value)}`);
}

function write(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${content.trim()}\n`);
}

function removeGeneratedFiles(directory: string, extension: string): void {
  mkdirSync(directory, { recursive: true });
  for (const file of readdirSync(directory)) {
    const path = join(directory, file);
    if (
      file.endsWith(extension) &&
      readFileSync(path, "utf8").includes("generate-demo-catalog.ts")
    ) {
      unlinkSync(path);
    }
  }
}

function meta(title: string, pages: readonly string[]): string {
  const pageLines = pages
    .map((page) => `    ${JSON.stringify(page)},`)
    .join("\n");

  return `import { defineMeta } from "blume";

export default defineMeta({
  pages: [
${pageLines}
  ],
  title: ${JSON.stringify(title)},
});`;
}

function registryCommand(demo: DemoCatalogEntry): string {
  return `bunx shadcn@latest add @protoform/${demo.registryName}`;
}

function registryItem(name: string): string {
  return `@protoform/${name}`;
}

function docsSlug(demo: DemoCatalogEntry): string {
  return demo.category === "aip" ? demo.slug : `example-${demo.slug}`;
}

function evidenceFor(demo: DemoCatalogEntry): string {
  return demo.requirementIds
    .map((requirementId) => {
      const requirement = readinessRequirements.find(
        (candidate) => candidate.id === requirementId
      );
      if (requirement?.status !== "verified") {
        throw new Error(`Missing verified requirement ${requirementId}`);
      }
      return `- \`${requirement.id}\` — \`${requirement.evidence.file}\`, “${requirement.evidence.testName}”`;
    })
    .join("\n");
}

function liveComponent(demo: DemoCatalogEntry): string {
  const focusedExamples: Record<string, string> = {
    "cel-re2": "examples/learning/cel-re2-form",
    "credential-redaction": "examples/complex/complex-form",
    "performance-bundle": "examples/kitchen-sink/kitchen-sink-form",
    "protobuf-nested-collections": "examples/nested/deeply-nested-form",
    "protobuf-oneof": "examples/learning/oneof-form",
    "responsive-cross-browser": "examples/kitchen-sink/kitchen-sink-form",
    "server-errors": "examples/basic/basic-form",
    stepper: "examples/learning/two-step-form",
  };

  const path =
    focusedExamples[demo.slug] ??
    `registry/base-nova/protoform/demo/catalog/${demo.slug}`;
  return `<Component path="${path}" />`;
}

function pageFor(demo: DemoCatalogEntry): string {
  const isAip = demo.category === "aip";
  const officialSource = isAip
    ? `\n[Read the canonical ${demo.title.split(" ")[0]} specification](https://google.aip.dev/${demo.requirementIds[0]?.slice(4)}).`
    : "";
  const engineNote =
    demo.engine === "react-hook-form"
      ? "This example uses Protoform's default React Hook Form adapter."
      : `This is an explicitly labeled ${engineLabels[demo.engine]} interoperability example; React Hook Form remains the default elsewhere.`;

  return `---
title: ${JSON.stringify(demo.title)}
description: ${JSON.stringify(demo.description)}
---

${generatedHeader}

${demo.description}
${officialSource}

## Try it

${demo.tryIt}

<div className="my-8 border-y border-border/60 py-8">
  ${liveComponent(demo)}
</div>

## Form engine

${engineNote}

## Install this example

\`\`\`bash
${registryCommand(demo)}
\`\`\`

The registry item installs this focused example and its shared demo runtime. Copy it, rename it, and
replace the fixture contract with your own generated descriptor.

## Executable compatibility evidence

The live form is visual evidence. These automated checks prove the underlying contract:

${evidenceFor(demo)}
`;
}

function indexPage(
  title: string,
  description: string,
  demos: readonly DemoCatalogEntry[]
): string {
  const rows = demos
    .map(
      (demo) =>
        `| [${demo.title}](/docs/${docsSlug(demo)}) | ${demo.description} | \`@protoform/${demo.registryName}\` |`
    )
    .join("\n");

  return `---
title: ${JSON.stringify(title)}
description: ${JSON.stringify(description)}
---

${generatedHeader}

${description}

Every page has one focused live form, an independent registry install, and links to executable
compatibility evidence.

| Example | Focus | Registry item |
| --- | --- | --- |
${rows}
`;
}

function wrapperName(slug: string): string {
  return `${slug
    .split("-")
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("")}Demo`;
}

const engineLabels = {
  "final-form": "Final Form",
  formik: "Formik",
  "react-hook-form": "React Hook Form",
  "tanstack-form": "TanStack Form",
} as const;

function tanStackRegistryWrapper(): string {
  return `${generatedSourceHeader}
'use client';

export const client = 'only';

import { formatSubmittedValue } from '../../lib/protobuf-provider';
import { useState } from 'react';

import { Alert, AlertDescription, AlertTitle } from '@/registry/base-nova/protoform/components/alert';
import { Badge } from '@/registry/base-nova/protoform/components/badge';
import { Button } from '@/registry/base-nova/protoform/components/button';
import { Field, FieldError, FieldLabel } from '@/registry/base-nova/protoform/components/field';
import { Input } from '@/registry/base-nova/protoform/components/input';
import { useProtoForm } from '@/registry/base-nova/protoform/hooks/use-proto-form-tanstack';
import { EmailContractSchema } from '@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/conformance_pb';

function errorMessage(error: unknown): string | undefined {
  if (typeof error === 'string') {
    return error;
  }
  if (error && typeof error === 'object') {
    const message = Reflect.get(error, 'message');
    return typeof message === 'string' ? message : undefined;
  }
  return;
}

export function TanstackFormDemo() {
  const [submittedValue, setSubmittedValue] = useState<string>();
  const form = useProtoForm(EmailContractSchema, {
    defaultValues: { email: '' },
    onSubmit: ({ value }) => {
      setSubmittedValue(formatSubmittedValue(form.createMessage(value)));
    },
  });

  return (
    <div className="space-y-6">
      <Badge variant="primary-inverted">TanStack Form interop</Badge>
      <form
        className="space-y-6"
        onSubmit={(event) => {
          event.preventDefault();
          event.stopPropagation();
          form.handleSubmit();
        }}
      >
        <form.Field name="email">
          {(field) => {
            const messages = field.state.meta.errors.map(errorMessage).filter((message): message is string => Boolean(message));
            const invalid = messages.length > 0;
            return (
              <Field data-invalid={invalid}>
                <FieldLabel htmlFor={field.name} required>Email</FieldLabel>
                <Input
                  aria-invalid={invalid || undefined}
                  id={field.name}
                  name={field.name}
                  onBlur={field.handleBlur}
                  onChange={(event) => field.handleChange(event.target.value)}
                  placeholder="ada@example.com"
                  type="email"
                  value={field.state.value}
                />
                <FieldError>{messages.join('\\n')}</FieldError>
              </Field>
            );
          }}
        </form.Field>
        <Button type="submit">Validate with TanStack Form</Button>
      </form>
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription><pre className="whitespace-pre-wrap text-xs">{submittedValue}</pre></AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default TanstackFormDemo;`;
}

function formikRegistryWrapper(): string {
  return `${generatedSourceHeader}
'use client';

export const client = 'only';

import { createFormikValidator } from '../../lib/core';
import { createProtoFormSchema, formatSubmittedValue } from '../../lib/protobuf-provider';
import { Formik } from "formik";
import { useState } from 'react';

import { Alert, AlertDescription, AlertTitle } from '@/registry/base-nova/protoform/components/alert';
import { Badge } from '@/registry/base-nova/protoform/components/badge';
import { Button } from '@/registry/base-nova/protoform/components/button';
import { Field, FieldError, FieldLabel } from '@/registry/base-nova/protoform/components/field';
import { Input } from '@/registry/base-nova/protoform/components/input';
import { EmailContractSchema } from '@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/conformance_pb';

interface EmailValues {
  email: string;
}

const schema = createProtoFormSchema<EmailValues, typeof EmailContractSchema>(EmailContractSchema);
const validate = createFormikValidator(schema);

export function FormikDemo() {
  const [submittedValue, setSubmittedValue] = useState<string>();

  return (
    <div className="space-y-6">
      <Badge variant="primary-inverted">Formik interop</Badge>
      <Formik<EmailValues>
        initialValues={{ email: '' }}
        onSubmit={async (values) => {
          const result = await schema['~standard'].validate(values);
          if (!result.issues) {
            setSubmittedValue(formatSubmittedValue(result.value));
          }
        }}
        validate={validate}
      >
        {({ errors, handleBlur, handleChange, handleSubmit, isSubmitting, touched, values }) => {
          const message = touched.email && typeof errors.email === 'string' ? errors.email : undefined;
          return (
            <form className="space-y-6" onSubmit={handleSubmit}>
              <Field data-invalid={Boolean(message)}>
                <FieldLabel htmlFor="formik-email" required>Email</FieldLabel>
                <Input
                  aria-invalid={Boolean(message) || undefined}
                  id="formik-email"
                  name="email"
                  onBlur={handleBlur}
                  onChange={handleChange}
                  placeholder="ada@example.com"
                  type="email"
                  value={values.email}
                />
                <FieldError>{message}</FieldError>
              </Field>
              <Button isLoading={isSubmitting} type="submit">Validate with Formik</Button>
            </form>
          );
        }}
      </Formik>
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription><pre className="whitespace-pre-wrap text-xs">{submittedValue}</pre></AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default FormikDemo;`;
}

function finalFormRegistryWrapper(): string {
  return `${generatedSourceHeader}
'use client';

export const client = 'only';

import { createFinalFormValidator } from '../../lib/core';
import { createProtoFormSchema, formatSubmittedValue } from '../../lib/protobuf-provider';
import { useState } from 'react';
import { Field as FinalField, Form as FinalForm } from "react-final-form";

import { Alert, AlertDescription, AlertTitle } from '@/registry/base-nova/protoform/components/alert';
import { Badge } from '@/registry/base-nova/protoform/components/badge';
import { Button } from '@/registry/base-nova/protoform/components/button';
import { Field, FieldError, FieldLabel } from '@/registry/base-nova/protoform/components/field';
import { Input } from '@/registry/base-nova/protoform/components/input';
import { EmailContractSchema } from '@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/conformance_pb';

interface EmailValues {
  email: string;
}

const schema = createProtoFormSchema<EmailValues, typeof EmailContractSchema>(EmailContractSchema);
const validate = createFinalFormValidator(schema);

export function FinalFormDemo() {
  const [submittedValue, setSubmittedValue] = useState<string>();

  return (
    <div className="space-y-6">
      <Badge variant="primary-inverted">Final Form interop</Badge>
      <FinalForm<EmailValues>
        initialValues={{ email: '' }}
        onSubmit={async (values) => {
          const result = await schema['~standard'].validate(values);
          if (!result.issues) {
            setSubmittedValue(formatSubmittedValue(result.value));
          }
        }}
        validate={validate}
      >
        {({ handleSubmit, submitting }) => (
          <form className="space-y-6" onSubmit={handleSubmit}>
            <FinalField<string> name="email">
              {({ input, meta }) => {
                const message = (meta.touched || meta.submitFailed) && typeof meta.error === 'string' ? meta.error : undefined;
                return (
                  <Field data-invalid={Boolean(message)}>
                    <FieldLabel htmlFor="final-form-email" required>Email</FieldLabel>
                    <Input
                      {...input}
                      aria-invalid={Boolean(message) || undefined}
                      id="final-form-email"
                      placeholder="ada@example.com"
                      type="email"
                    />
                    <FieldError>{message}</FieldError>
                  </Field>
                );
              }}
            </FinalField>
            <Button isLoading={submitting} type="submit">Validate with Final Form</Button>
          </form>
        )}
      </FinalForm>
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription><pre className="whitespace-pre-wrap text-xs">{submittedValue}</pre></AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default FinalFormDemo;`;
}

function reactHookFormRegistryWrapper(demo: DemoCatalogEntry): string {
  const methodImport =
    demo.slug === "bufbuild-descriptors"
      ? "\nimport { LibraryService } from '@/registry/base-nova/protoform/demo/runtime/gen/protoform/conformance/v1/aip_pb';\n"
      : "";
  const methodDeclaration =
    demo.slug === "bufbuild-descriptors"
      ? "\nconst method = LibraryService.method.createBook;\n"
      : "";
  const schemaDeclaration =
    demo.slug === "bufbuild-descriptors"
      ? `  const { defaultValues } = getDemoSchema(${JSON.stringify(demo.schemaKey)});
  const schema = method.input;`
      : `  const { defaultValues, schema } = getDemoSchema(${JSON.stringify(demo.schemaKey)});`;
  const methodBadge =
    demo.slug === "bufbuild-descriptors"
      ? '\n        <Badge variant="outline">{method.methodKind} RPC</Badge>'
      : "";
  const methodShape =
    demo.slug === "bufbuild-descriptors"
      ? `
      <div
        aria-label="RPC method shape"
        className="grid gap-3 rounded-lg border border-border bg-muted/30 p-4 text-sm sm:grid-cols-2"
      >
        <div>
          <p className="font-medium text-foreground">{method.name}</p>
          <p className="text-muted-foreground">Generated method descriptor</p>
        </div>
        <dl className="grid gap-2">
          <div>
            <dt className="font-medium text-foreground">Input</dt>
            <dd className="break-all text-muted-foreground">
              {method.input.typeName}
            </dd>
          </div>
          <div>
            <dt className="font-medium text-foreground">Output</dt>
            <dd className="break-all text-muted-foreground">
              {method.output.typeName}
            </dd>
          </div>
        </dl>
      </div>`
      : "";

  return `${generatedSourceHeader}
'use client';

export const client = 'only';

import { formatSubmittedValue } from '../../lib/protobuf-provider';
import { useState } from 'react';

import {
  Alert,
  AlertDescription,
  AlertTitle,
} from '@/registry/base-nova/protoform/components/alert';
import { AutoForm } from '@/registry/base-nova/protoform/components/auto-form';
import { Badge } from '@/registry/base-nova/protoform/components/badge';
import { getDemoSchema } from '@/registry/base-nova/protoform/demo/runtime/demo-schemas';
${methodImport}${methodDeclaration}
export function ${wrapperName(demo.slug)}() {
  const [submittedValue, setSubmittedValue] = useState<string>();
${schemaDeclaration}

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-2">
        <Badge variant="primary-inverted">React Hook Form</Badge>
        <Badge variant="outline">Live protobuf contract</Badge>${methodBadge}
      </div>${methodShape}
      <p className="text-muted-foreground text-sm">
        {${JSON.stringify(demo.tryIt)}}
      </p>
      <AutoForm
        defaultValues={defaultValues}
        formOptions={{ mode: 'onBlur', reValidateMode: 'onChange' }}
        onFieldChange={() => setSubmittedValue(undefined)}
        onSubmit={(values) => setSubmittedValue(formatSubmittedValue(values))}
        schema={schema}
        withSubmit
      />
      {submittedValue ? (
        <Alert role="status" variant="success">
          <AlertTitle>Submitted protobuf value</AlertTitle>
          <AlertDescription>
            <pre className="max-h-80 max-w-full overflow-auto whitespace-pre-wrap text-xs">
              {submittedValue}
            </pre>
          </AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}

export default ${wrapperName(demo.slug)};`;
}

function registryWrapper(demo: DemoCatalogEntry): string {
  if (demo.engine === "tanstack-form") {
    return tanStackRegistryWrapper();
  }
  if (demo.engine === "formik") {
    return formikRegistryWrapper();
  }
  if (demo.engine === "final-form") {
    return finalFormRegistryWrapper();
  }
  return reactHookFormRegistryWrapper(demo);
}

function dependenciesForDemo(demo: DemoCatalogEntry): string[] {
  switch (demo.engine) {
    case "formik":
      return ["formik"];
    case "final-form":
      return ["final-form", "react-final-form"];
    case "tanstack-form":
      return ["@tanstack/react-form"];
    case "react-hook-form":
      return [];
    default:
      return assertNever(demo.engine);
  }
}

function generateDocs(): void {
  removeGeneratedFiles(aipDirectory, ".mdx");
  const aipDemos = demoCatalog.filter((demo) => demo.category === "aip");
  for (const demo of aipDemos) {
    write(join(aipDirectory, `${docsSlug(demo)}.mdx`), pageFor(demo));
  }
  write(
    join(aipDirectory, "aip-example-catalog.mdx"),
    indexPage(
      "AIP demo catalog",
      "One focused live React Hook Form example for every form-applicable General AIP.",
      aipDemos
    )
  );
  write(
    join(aipDirectory, "meta.ts"),
    meta("AIP examples", ["aip-example-catalog", ...aipDemos.map(docsSlug)])
  );

  const featureCategories = [
    ["protobuf", "Protobuf"],
    ["protovalidate", "Protovalidate"],
    ["cel", "CEL"],
    ["production", "Production and interoperability"],
  ] as const;
  const featureDemos = demoCatalog.filter((demo) => demo.category !== "aip");

  removeGeneratedFiles(featureDirectory, ".mdx");
  write(
    join(featureDirectory, "feature-example-catalog.mdx"),
    indexPage(
      "Feature demo catalog",
      "Focused visual demos spanning Protobuf, Protovalidate, CEL, form workflows, and production behavior.",
      featureDemos
    )
  );
  write(
    join(featureDirectory, "meta.ts"),
    meta("Feature examples", [
      "feature-example-catalog",
      ...featureCategories.map(([category]) => category),
    ])
  );

  for (const [category, title] of featureCategories) {
    const directory = join(featureDirectory, `(${category})`);
    removeGeneratedFiles(directory, ".mdx");
    const demos = featureDemos.filter((demo) =>
      category === "production"
        ? demo.category === "production" || demo.category === "interop"
        : demo.category === category
    );
    for (const demo of demos) {
      write(join(directory, `${docsSlug(demo)}.mdx`), pageFor(demo));
    }
    write(join(directory, "meta.ts"), meta(title, demos.map(docsSlug)));
  }
}

function generateRegistryRuntime(): string[] {
  const generatedFiles = [
    "buf/validate/validate_pb.ts",
    "google/api/field_behavior_pb.ts",
    "google/api/field_info_pb.ts",
    "google/api/resource_pb.ts",
    "google/rpc/status_pb.ts",
    "protoform/conformance/v1/aip_form.ts",
    "protoform/conformance/v1/aip_pb.ts",
    "protoform/conformance/v1/conformance_pb.ts",
    "protoform/conformance/v1/editions_pb.ts",
    "protoform/conformance/v1/predefined_pb.ts",
  ];

  for (const file of generatedFiles) {
    const target = join(registryRuntimeDirectory, "gen", file);
    write(target, readFileSync(join(root, "conformance/gen", file), "utf8"));
  }

  const schemaKeys = [
    ...new Set(demoCatalog.map((demo) => demo.schemaKey)),
  ].toSorted();
  const schemaType = `export type DemoSchemaKey =\n${schemaKeys
    .map((key) => `  | ${JSON.stringify(key)}`)
    .join("\n")};`;
  const schemaSource = readFileSync(
    join(root, "examples/catalog/demo-schemas.ts"),
    "utf8"
  )
    .replaceAll(
      "../../conformance/gen/protoform/conformance/v1/",
      "./gen/protoform/conformance/v1/"
    )
    .replace(
      'import type { DemoSchemaKey } from "./demo-catalog.js";',
      schemaType
    );
  write(join(registryRuntimeDirectory, "demo-schemas.ts"), schemaSource);

  return [
    "registry/base-nova/protoform/demo/runtime/demo-schemas.ts",
    ...generatedFiles.map(
      (file) => `registry/base-nova/protoform/demo/runtime/gen/${file}`
    ),
  ];
}

function generateRegistry(): void {
  removeGeneratedFiles(registryDemoDirectory, ".tsx");
  for (const demo of demoCatalog) {
    write(
      join(registryDemoDirectory, `${demo.slug}.tsx`),
      registryWrapper(demo)
    );
  }

  const runtimeFiles = generateRegistryRuntime();
  const registryPath = join(root, "registry.json");
  const registry = JSON.parse(readFileSync(registryPath, "utf8")) as {
    items: Array<Record<string, unknown> & { name: string }>;
  };
  const generatedNames = new Set([
    "protoform-demo-runtime",
    ...demoCatalog.map((demo) => demo.registryName),
  ]);
  const items = registry.items.filter((item) => {
    if (generatedNames.has(item.name)) {
      return false;
    }
    const files = Array.isArray(item.files) ? item.files : [];
    return !files.some(
      (file) =>
        typeof file === "object" &&
        file !== null &&
        "path" in file &&
        typeof file.path === "string" &&
        file.path.includes("/protoform/demo/catalog/")
    );
  });
  const umbrella = items.find((item) => item.name === "protoform-examples");
  if (!umbrella) {
    throw new Error("registry.json is missing protoform-examples");
  }
  umbrella.registryDependencies = [
    registryItem("protoform"),
    ...demoCatalog.map((demo) => registryItem(demo.registryName)),
  ];

  items.push({
    dependencies: ["@bufbuild/protobuf", "react", "react-hook-form"],
    description:
      "Shared fixture descriptors and generated compatibility contracts for focused Protoform demos.",
    files: runtimeFiles.map((path) => ({
      path,
      target: `~/components/protoform-examples/runtime/${path.replace(
        "registry/base-nova/protoform/demo/runtime/",
        ""
      )}`,
      type: path.endsWith(".tsx") ? "registry:component" : "registry:lib",
    })),
    name: "protoform-demo-runtime",
    registryDependencies: [registryItem("protoform")],
    title: "Protoform demo runtime",
    type: "registry:block",
  });
  items.push(
    ...demoCatalog.map((demo) => {
      const registryDependencies = [registryItem("protoform-demo-runtime")];
      if (demo.engine === "tanstack-form") {
        registryDependencies.push(registryItem("use-proto-form-tanstack"));
      }

      return {
        dependencies: dependenciesForDemo(demo),
        description: demo.description,
        files: [
          {
            path: `registry/base-nova/protoform/demo/catalog/${demo.slug}.tsx`,
            target: `~/components/protoform-examples/${demo.slug}.tsx`,
            type: "registry:component",
          },
        ],
        name: demo.registryName,
        registryDependencies,
        title: demo.title,
        type: "registry:example",
      };
    })
  );
  registry.items = items;
  writeFileSync(registryPath, `${JSON.stringify(registry, null, 2)}\n`);
  execFileSync("bunx", ["biome", "format", registryPath, "--write"], {
    cwd: root,
    stdio: "ignore",
  });
}

generateDocs();
generateRegistry();
