// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  pages: [
    "index",
    "start-here",
    "examples",
    "presets",
    "feature-examples",
    "aip-examples",
    "build-forms",
    "validation-and-apis",
    "migrations",
    "production",
  ],
  title: "Protoform",
};
