// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  pages: ["protovalidate-examples"],
  title: "Protovalidate",
};
