// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  pages: ["getting-started", "bookstore", "registry-install"],
  title: "從這裡開始",
};
