// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  pages: [
    "auto-form",
    "steppers",
    "oneof-edge-cases",
    "react-hook-form",
    "tanstack-form",
    "formik",
    "final-form",
  ],
  title: "Tworzenie formularzy",
};
